//! KvStore non-transactional API.

use std::{
    borrow::Borrow,
    hash::Hash,
    marker::PhantomData,
    sync::{Arc, RwLockReadGuard},
};

use crate::{
    Error, KvStore, Owner, Result, SingletonTransaction, TableTransaction,
    iter::{Keys, KeysAndValues, Values},
    operations::{SingletonRef, TableRef},
    schema,
    storage::Storage,
    transactions::SchemaTransaction,
};

/// Access singleton data in the store.
///
/// `S` describes the data and instances are generated by the schema macros.
pub struct Singleton<
    TableStorage: schema::GeneratedStorage + 'static,
    S: schema::SingletonDesc<Storage = TableStorage>,
> {
    store: Arc<KvStore<TableStorage>>,
    desc: PhantomData<S>,
}

impl<
    TableStorage: schema::GeneratedStorage + 'static,
    S: schema::SingletonDesc<Storage = TableStorage>,
> Singleton<TableStorage, S>
{
    #[doc(hidden)]
    pub fn new(store: Arc<KvStore<TableStorage>>) -> Self {
        Singleton {
            store,
            desc: PhantomData,
        }
    }

    fn store(&self) -> &KvStore<TableStorage> {
        &self.store
    }

    fn read_lock(&self) -> RwLockReadGuard<'_, Storage<TableStorage>> {
        self.store.get_read_lock()
    }

    /// Subscribe to a singleton key-value pair.
    pub fn subscribe(
        &self,
        subscriber: impl Into<crate::Subscriber>,
    ) -> Result<crate::Subscription> {
        let subs = &self.read_lock().subscriptions;
        let id = subs.create_singleton_subscription::<S>(subscriber.into())?;

        Ok(id)
    }

    /// Subscribe to a singleton key-value pair and send the current value (if any) to the subscriber.
    pub fn subscribe_and_notify(
        &self,
        subscriber: impl Into<crate::Subscriber>,
    ) -> Result<crate::Subscription> {
        let storage = self.read_lock();
        let subs = &storage.subscriptions;
        let id = subs.create_singleton_subscription::<S>(subscriber.into())?;

        crate::pub_sub::send_current_singleton::<S>(subs, &storage, id);

        Ok(id)
    }

    /// Unsubscribe to a singleton key-value pair.
    pub fn unsubscribe(&self, subscription: crate::Subscription) {
        self.read_lock()
            .subscriptions
            .remove_singleton_subscription::<S>(subscription)
    }

    /// Get a single value from the store by cloning the value.
    ///
    /// Returns `None` if there is no value for the specified key.
    pub fn get(&self, _owner: Owner) -> Option<S::Value>
    where
        S::Value: Clone,
    {
        SingletonRef::<S>::from_storage(&self.read_lock())
            .get()
            .cloned()
    }

    /// Get immutable access to a value in the store by reference.
    ///
    /// Returns `None` (and does not call `f`) if there is no value for the specified key.
    pub fn with<T>(&self, _owner: Owner, f: impl FnOnce(&S::Value) -> T) -> Option<T> {
        SingletonRef::<S>::from_storage(&self.read_lock())
            .get()
            .map(f)
    }

    /// Get mutable access to a value in the store by reference.
    ///
    /// Returns `None` (and does not call `f`) if there is no value for the specified key.
    pub fn with_mut<T>(&self, owner: Owner, f: impl FnOnce(&mut S::Value) -> T) -> Option<T>
    where
        S::Value: Clone + PartialEq,
    {
        // Should never panic since transaction should only fail on index inserts.
        in_singleton_txn::<_, S, _>(self.store(), owner, |view| view.with_mut(f)).unwrap()
    }

    /// Insert a single value into the store.
    pub fn insert(&self, owner: Owner, value: S::Value) {
        // Should never panic since transaction should only fail on index inserts.
        in_singleton_txn::<_, S, _>(self.store(), owner, |view| view.insert(value)).unwrap()
    }

    /// Remove a single value from the store.
    pub fn remove(&self, owner: Owner) {
        // Should never panic since transaction should only fail on index inserts.
        in_singleton_txn::<_, S, _>(self.store(), owner, |view| view.remove()).unwrap()
    }
}

/// Apply `f` to `S`'s view of a transaction which contains only that operation, and commit it.
///
/// Returns the error from committing, if there is one. This is how the non-transactional singleton
/// operations get their atomicity: each one is a single-operation transaction.
fn in_singleton_txn<TableStorage, S, T>(
    store: &KvStore<TableStorage>,
    owner: Owner,
    f: impl FnOnce(&mut SingletonTransaction<'_, TableStorage, S>) -> T,
) -> Result<T>
where
    TableStorage: schema::GeneratedStorage + 'static,
    S: schema::SingletonDesc<Storage = TableStorage>,
{
    let mut txn = store.begin_transaction(owner);
    let result = f(S::make_txn_view(&mut txn));
    txn.commit()?;
    Ok(result)
}

/// Access tabular data in the store.
///
/// `D` describes the table and instances are generated by the schema macros.
pub struct Table<
    TableStorage: schema::GeneratedStorage + 'static,
    D: schema::TableDesc<Storage = TableStorage>,
> {
    store: Arc<KvStore<TableStorage>>,
    desc: PhantomData<D>,
}

impl<TableStorage: schema::GeneratedStorage + 'static, D: schema::TableDesc<Storage = TableStorage>>
    Table<TableStorage, D>
{
    #[doc(hidden)]
    pub fn new(store: Arc<KvStore<TableStorage>>) -> Self {
        Table {
            store,
            desc: PhantomData,
        }
    }

    fn store(&self) -> &KvStore<TableStorage> {
        &self.store
    }

    /// Apply `f` to the table (not as part of any transaction).
    fn read<T>(&self, f: impl FnOnce(TableRef<'_, D>) -> T) -> T {
        read_table(self.store(), f)
    }

    /// The number of key/value pairs in the table.
    pub fn len(&self) -> usize {
        self.read(|t| t.len())
    }

    /// True if the table is empty.
    pub fn is_empty(&self) -> bool {
        self.read(|t| t.is_empty())
    }

    /// Clear a table by removing all its KVs.
    pub fn clear(&self, owner: Owner) {
        // Should never panic since transaction should only fail on index inserts.
        in_table_txn::<_, D, _>(self.store(), owner, |view| view.clear()).unwrap()
    }

    /// Get a row of the table from the store by cloning the value.
    ///
    /// Returns `None` if there is no value for the specified key.
    pub fn get<Q>(&self, _owner: Owner, key: &Q) -> Option<D::Value>
    where
        D::Value: Clone,
        D::Key: Borrow<Q>,
        Q: ?Sized + Hash + Eq,
    {
        self.read(|t| t.get(key).cloned())
    }

    /// Get immutable access to a row of the table in the store by reference.
    ///
    /// Returns `None` (and does not call `f`) if there is no value for the specified key.
    pub fn with<Q, T>(&self, _owner: Owner, key: &Q, f: impl FnOnce(&D::Value) -> T) -> Option<T>
    where
        D::Key: Borrow<Q>,
        Q: ?Sized + Hash + Eq,
    {
        self.read(|t| t.get(key).map(f))
    }

    /// Insert a `value` into the table.
    ///
    /// Panics if the value is already indexed with the same index key.
    pub fn insert(&self, owner: Owner, key: D::Key, value: D::Value) {
        self.try_insert(owner, key, value).unwrap();
    }

    /// Insert a `value` into the table.
    ///
    /// Returns an error if `insert` would panic.
    pub fn try_insert(&self, owner: Owner, key: D::Key, value: D::Value) -> Result<()> {
        in_table_txn::<_, D, _>(self.store(), owner, |view| view.insert(key, value))
    }

    /// Get mutable access to a row of the table in the store in the store.
    ///
    /// Returns `Error::NotPresent` (and does not call `f`) if there is no value for the specified key.
    pub fn with_mut<Q, T>(
        &self,
        owner: Owner,
        key: &Q,
        f: impl FnOnce(&mut D::Value) -> T,
    ) -> Result<T>
    where
        D::Key: Borrow<Q>,
        Q: ?Sized + Hash + Eq + ToOwned<Owned = D::Key>,
        D::Value: Clone + PartialEq,
    {
        in_table_txn::<_, D, _>(self.store(), owner, |view| view.with_mut(key, f))?
            .ok_or(Error::NotPresent)
    }

    /// Remove a row from the table.
    pub fn remove<Q>(&self, owner: Owner, key: &Q)
    where
        D::Key: Borrow<Q>,
        Q: ?Sized + Hash + Eq + ToOwned<Owned = D::Key>,
    {
        // Should never panic since transaction should only fail on index inserts.
        in_table_txn::<_, D, _>(self.store(), owner, |view| view.remove(key)).unwrap()
    }

    /// Pass an iterator over all the key/value pairs in the table to `f`.
    ///
    /// The store is locked for reading while `f` is called. Access is scoped by a closure (rather
    /// than returning an iterator) so that the yielded references cannot outlive the lock. Use
    /// `iter` within a (read-only) transaction for an iterator.
    pub fn with_iter<F, T>(&self, _owner: Owner, f: F) -> T
    where
        F: for<'a> FnOnce(&mut dyn Iterator<Item = (&'a D::Key, &'a D::Value)>) -> T,
    {
        self.read(|t| f(&mut t.iter::<KeysAndValues>()))
    }

    /// Pass an iterator over all the keys in the table to `f`.
    ///
    /// See `with_iter` for why access is scoped by a closure.
    pub fn with_keys<F, T>(&self, _owner: Owner, f: F) -> T
    where
        F: for<'a> FnOnce(&mut dyn Iterator<Item = &'a D::Key>) -> T,
    {
        self.read(|t| f(&mut t.iter::<Keys>()))
    }

    /// Pass an iterator over all the values in the table to `f`.
    ///
    /// See `with_iter` for why access is scoped by a closure.
    pub fn with_values<F, T>(&self, _owner: Owner, f: F) -> T
    where
        F: for<'a> FnOnce(&mut dyn Iterator<Item = &'a D::Value>) -> T,
    {
        self.read(|t| f(&mut t.iter::<Values>()))
    }

    /// Pass an iterator over all the key/value pairs in the table, with mutable access to the
    /// values, to `f`.
    pub fn with_iter_mut<F, T>(&self, owner: Owner, f: F) -> T
    where
        F: for<'a> FnOnce(&mut dyn Iterator<Item = (&'a D::Key, &'a mut D::Value)>) -> T,
        D::Value: Clone + PartialEq,
    {
        // Should never panic since transaction should only fail on index inserts.
        in_table_txn::<_, D, _>(self.store(), owner, |view| view.with_iter_mut(f)).unwrap()
    }
}

impl<TableStorage: schema::GeneratedStorage + 'static, D: schema::Indexable<Storage = TableStorage>>
    Table<TableStorage, D>
{
    /// Access the table via its indexes.
    ///
    /// Returns a macro-generated struct with a field for each index declared for the table; each
    /// field is an [`Index`](crate::Index) which gives access to the table using that index's key.
    ///
    /// # Example:
    ///
    /// ```rust,ignore
    /// let value = store.Foo.indexes().bar.get(OWNER, key).unwrap();
    /// ```
    ///
    /// Here `Foo` is a table and `bar` is an index over `Foo` using the `bar` field as foreign key.
    pub fn indexes(&self) -> D::Indexes<'_> {
        self.store().into()
    }
}

impl<
    TableStorage: schema::GeneratedStorage + 'static,
    D: schema::Notifiable<Storage = TableStorage>,
> Table<TableStorage, D>
{
    /// Subscribe to the whole table.
    pub fn subscribe(&self, subscriber: impl Into<crate::Subscriber>) -> Result<crate::Subscription>
    where
        D::Key: Send,
    {
        let subs = &self.store().get_read_lock().subscriptions;
        let id = subs.create_table_subscription_all::<D>(subscriber.into())?;
        Ok(id)
    }

    /// Unsubscribe from the table (whole table or single key).
    pub fn unsubscribe(&self, subscription: crate::Subscription) {
        self.store()
            .get_read_lock()
            .subscriptions
            .remove_table_subscription::<D>(subscription);
    }

    /// Subscribe to a specific key in the table.
    pub fn subscribe_key(
        &self,
        subscriber: impl Into<crate::Subscriber>,
        key: D::Key,
    ) -> Result<crate::Subscription>
    where
        D::Key: Send,
    {
        let subs = &self.store().get_read_lock().subscriptions;
        let id = subs.create_table_subscription::<D>(key, subscriber.into())?;
        Ok(id)
    }

    /// Subscribe to a specific key in the table and send the current value (if any) to the subscriber.
    pub fn subscribe_key_and_notify(
        &self,
        subscriber: impl Into<crate::Subscriber>,
        key: D::Key,
    ) -> Result<crate::Subscription>
    where
        D::Key: Send,
    {
        let storage = self.store().get_read_lock();
        let subs = &storage.subscriptions;
        let id = subs.create_table_subscription::<D>(key.clone(), subscriber.into())?;

        crate::pub_sub::send_current::<D>(subs, &storage, key, id);

        Ok(id)
    }
}

/// Apply `f` to `D`'s table in `store` (not as part of any transaction).
fn read_table<TableStorage, D, T>(
    store: &KvStore<TableStorage>,
    f: impl FnOnce(TableRef<'_, D>) -> T,
) -> T
where
    TableStorage: schema::GeneratedStorage + 'static,
    D: schema::TableDesc<Storage = TableStorage>,
{
    let guard = store.get_read_lock();
    f(TableRef::from_storage(&guard))
}

/// Apply `f` to `D`'s view of a transaction which contains only that operation, and commit it.
///
/// Returns the error from committing, if there is one. This is how the non-transactional table
/// operations get their atomicity: each one is a single-operation transaction.
fn in_table_txn<TableStorage, D, T>(
    store: &KvStore<TableStorage>,
    owner: Owner,
    f: impl FnOnce(&mut TableTransaction<'_, TableStorage, D>) -> T,
) -> Result<T>
where
    TableStorage: schema::GeneratedStorage + 'static,
    D: schema::TableDesc<Storage = TableStorage>,
{
    let mut txn = store.begin_transaction(owner);
    let result = f(D::make_txn_view(&mut txn));
    txn.commit()?;
    Ok(result)
}

/// A singleton in the store, accessed with a fixed owner.
///
/// The owner-carrying counterpart of [`Singleton`]: the operations are the same, but the owner is
/// supplied once (by the generated `StoreWithOwner`) rather than on each call. There is a field of this type in
/// the generated `StoreWithOwner` for each singleton in the schema.
pub struct SingletonWithOwner<
    'store,
    TableStorage: schema::GeneratedStorage + 'static,
    S: schema::SingletonDesc<Storage = TableStorage>,
> {
    store: &'store KvStore<TableStorage>,
    owner: Owner,
    desc: PhantomData<S>,
}

impl<
    'store,
    TableStorage: schema::GeneratedStorage + 'static,
    S: schema::SingletonDesc<Storage = TableStorage>,
> SingletonWithOwner<'store, TableStorage, S>
{
    #[doc(hidden)]
    pub fn new(store: &'store KvStore<TableStorage>, owner: Owner) -> Self {
        SingletonWithOwner {
            store,
            owner,
            desc: PhantomData,
        }
    }

    fn read_lock(&self) -> RwLockReadGuard<'store, Storage<TableStorage>> {
        self.store.get_read_lock()
    }

    /// Subscribe to a singleton key-value pair.
    pub fn subscribe(&self, subscriber: crate::Subscriber) -> Result<crate::Subscription> {
        let subs = &self.read_lock().subscriptions;
        let id = subs.create_singleton_subscription::<S>(subscriber)?;

        Ok(id)
    }

    /// Subscribe to a singleton key-value pair and send the current value (if any) to the subscriber.
    pub fn subscribe_and_notify(
        &self,
        subscriber: crate::Subscriber,
    ) -> Result<crate::Subscription> {
        let storage = self.read_lock();
        let subs = &storage.subscriptions;
        let id = subs.create_singleton_subscription::<S>(subscriber)?;

        crate::pub_sub::send_current_singleton::<S>(subs, &storage, id);

        Ok(id)
    }

    /// Unsubscribe to a singleton key-value pair.
    pub fn unsubscribe(&self, subscription: crate::Subscription) {
        self.read_lock()
            .subscriptions
            .remove_singleton_subscription::<S>(subscription)
    }

    /// Get a single value from the store by cloning the value.
    ///
    /// Returns `None` if there is no value for the specified key.
    pub fn get(&self) -> Option<S::Value>
    where
        S::Value: Clone,
    {
        SingletonRef::<S>::from_storage(&self.read_lock())
            .get()
            .cloned()
    }

    /// Get immutable access to a value in the store by reference.
    ///
    /// Returns `None` (and does not call `f`) if there is no value for the specified key.
    pub fn with<T>(&self, f: impl FnOnce(&S::Value) -> T) -> Option<T> {
        SingletonRef::<S>::from_storage(&self.read_lock())
            .get()
            .map(f)
    }

    /// Get mutable access to a value in the store by reference.
    ///
    /// Returns `None` (and does not call `f`) if there is no value for the specified key.
    pub fn with_mut<T>(&self, f: impl FnOnce(&mut S::Value) -> T) -> Option<T>
    where
        S::Value: Clone + PartialEq,
    {
        // Should never panic since transaction should only fail on index inserts.
        in_singleton_txn::<_, S, _>(self.store, self.owner, |view| view.with_mut(f)).unwrap()
    }

    /// Insert a single value into the store.
    pub fn insert(&self, value: S::Value) {
        // Should never panic since transaction should only fail on index inserts.
        in_singleton_txn::<_, S, _>(self.store, self.owner, |view| view.insert(value)).unwrap()
    }

    /// Remove a single value from the store.
    pub fn remove(&self) {
        // Should never panic since transaction should only fail on index inserts.
        in_singleton_txn::<_, S, _>(self.store, self.owner, |view| view.remove()).unwrap()
    }
}

/// A table of key/value pairs in the store, accessed with a fixed owner.
///
/// The owner-carrying counterpart of [`Table`]: the operations are the same, but the owner is
/// supplied once (by the generated `KvStoreWithOwner`) rather than on each call. There is a field of this type in
/// the generated `KvStoreWithOwner` for each table in the schema.
pub struct TableWithOwner<
    'store,
    TableStorage: schema::GeneratedStorage + 'static,
    D: schema::TableDesc<Storage = TableStorage>,
> {
    store: &'store KvStore<TableStorage>,
    owner: Owner,
    desc: PhantomData<D>,
}

impl<
    'store,
    TableStorage: schema::GeneratedStorage + 'static,
    D: schema::TableDesc<Storage = TableStorage>,
> TableWithOwner<'store, TableStorage, D>
{
    #[doc(hidden)]
    pub fn new(store: &'store KvStore<TableStorage>, owner: Owner) -> Self {
        TableWithOwner {
            store,
            owner,
            desc: PhantomData,
        }
    }

    fn read_lock(&self) -> RwLockReadGuard<'store, Storage<TableStorage>> {
        self.store.get_read_lock()
    }

    /// Apply `f` to the table (not as part of any transaction).
    fn read<T>(&self, f: impl FnOnce(TableRef<'_, D>) -> T) -> T {
        read_table(self.store, f)
    }

    /// The number of key/value pairs in the table.
    pub fn len(&self) -> usize {
        self.read(|t| t.len())
    }

    /// True if the table is empty.
    pub fn is_empty(&self) -> bool {
        self.read(|t| t.is_empty())
    }

    /// Clear a table by removing all its KVs.
    pub fn clear(&self) {
        // Should never panic since transaction should only fail on index inserts.
        in_table_txn::<_, D, _>(self.store, self.owner, |view| view.clear()).unwrap()
    }

    /// Get a row of the table from the store by cloning the value.
    ///
    /// Returns `None` if there is no value for the specified key.
    pub fn get<Q>(&self, key: &Q) -> Option<D::Value>
    where
        D::Value: Clone,
        D::Key: Borrow<Q>,
        Q: ?Sized + Hash + Eq,
    {
        self.read(|t| t.get(key).cloned())
    }

    /// Get immutable access to a row of the table in the store by reference.
    ///
    /// Returns `None` (and does not call `f`) if there is no value for the specified key.
    pub fn with<Q, T>(&self, key: &Q, f: impl FnOnce(&D::Value) -> T) -> Option<T>
    where
        D::Key: Borrow<Q>,
        Q: ?Sized + Hash + Eq,
    {
        self.read(|t| t.get(key).map(f))
    }

    /// Insert a `value` into the table.
    ///
    /// Panics if the value is already indexed with the same index key.
    pub fn insert(&self, key: D::Key, value: D::Value) {
        self.try_insert(key, value).unwrap();
    }

    /// Insert a `value` into the table.
    ///
    /// Returns an error if `insert` would panic.
    pub fn try_insert(&self, key: D::Key, value: D::Value) -> Result<()> {
        in_table_txn::<_, D, _>(self.store, self.owner, |view| view.insert(key, value))
    }

    /// Get mutable access to a row of the table in the store in the store.
    ///
    /// Returns `Error::NotPresent` (and does not call `f`) if there is no value for the specified key.
    pub fn with_mut<Q, T>(&self, key: &Q, f: impl FnOnce(&mut D::Value) -> T) -> Result<T>
    where
        D::Key: Borrow<Q>,
        Q: ?Sized + Hash + Eq + ToOwned<Owned = D::Key>,
        D::Value: Clone + PartialEq,
    {
        in_table_txn::<_, D, _>(self.store, self.owner, |view| view.with_mut(key, f))?
            .ok_or(Error::NotPresent)
    }

    /// Remove a row from the table.
    pub fn remove<Q>(&self, key: &Q)
    where
        D::Key: Borrow<Q>,
        Q: ?Sized + Hash + Eq + ToOwned<Owned = D::Key>,
    {
        // Should never panic since transaction should only fail on index inserts.
        in_table_txn::<_, D, _>(self.store, self.owner, |view| view.remove(key)).unwrap()
    }

    /// Pass an iterator over all the key/value pairs in the table to `f`.
    ///
    /// The store is locked for reading while `f` is called. Access is scoped by a closure (rather
    /// than returning an iterator) so that the yielded references cannot outlive the lock. Use
    /// `iter` within a (read-only) transaction for an iterator.
    pub fn with_iter<F, T>(&self, f: F) -> T
    where
        F: for<'a> FnOnce(&mut dyn Iterator<Item = (&'a D::Key, &'a D::Value)>) -> T,
    {
        self.read(|t| f(&mut t.iter::<KeysAndValues>()))
    }

    /// Pass an iterator over all the keys in the table to `f`.
    ///
    /// See `with_iter` for why access is scoped by a closure.
    pub fn with_keys<F, T>(&self, f: F) -> T
    where
        F: for<'a> FnOnce(&mut dyn Iterator<Item = &'a D::Key>) -> T,
    {
        self.read(|t| f(&mut t.iter::<Keys>()))
    }

    /// Pass an iterator over all the values in the table to `f`.
    ///
    /// See `with_iter` for why access is scoped by a closure.
    pub fn with_values<F, T>(&self, f: F) -> T
    where
        F: for<'a> FnOnce(&mut dyn Iterator<Item = &'a D::Value>) -> T,
    {
        self.read(|t| f(&mut t.iter::<Values>()))
    }

    /// Pass an iterator over all the key/value pairs in the table, with mutable access to the
    /// values, to `f`.
    pub fn with_iter_mut<F, T>(&self, f: F) -> T
    where
        F: for<'a> FnOnce(&mut dyn Iterator<Item = (&'a D::Key, &'a mut D::Value)>) -> T,
        D::Value: Clone + PartialEq,
    {
        // Should never panic since transaction should only fail on index inserts.
        in_table_txn::<_, D, _>(self.store, self.owner, |view| view.with_iter_mut(f)).unwrap()
    }
}

impl<
    'store,
    TableStorage: schema::GeneratedStorage + 'static,
    D: schema::Indexable<Storage = TableStorage>,
> TableWithOwner<'store, TableStorage, D>
{
    /// Access the table via its indexes.
    ///
    /// Returns a macro-generated struct with a field for each index declared for the table; each
    /// field is an [`IndexWithOwner`](crate::IndexWithOwner) which gives access to the table using
    /// that index's key.
    ///
    /// # Example:
    ///
    /// ```rust,ignore
    /// let value = store.with_owner(OWNER).Foo.indexes().bar.get(key).unwrap();
    /// ```
    ///
    /// Here `Foo` is a table and `bar` is an index over `Foo` using the `bar` field as foreign key.
    pub fn indexes(&self) -> D::IndexesWithOwner<'store> {
        (self.store, self.owner).into()
    }
}

impl<
    'store,
    TableStorage: schema::GeneratedStorage + 'static,
    D: schema::Notifiable<Storage = TableStorage>,
> TableWithOwner<'store, TableStorage, D>
{
    /// Subscribe to the whole table.
    pub fn subscribe(&self, subscriber: crate::Subscriber) -> Result<crate::Subscription>
    where
        D::Key: Send,
    {
        let subs = &self.read_lock().subscriptions;
        let id = subs.create_table_subscription_all::<D>(subscriber)?;
        Ok(id)
    }

    /// Unsubscribe from the table (whole table or single key).
    pub fn unsubscribe(&self, subscription: crate::Subscription) {
        self.read_lock()
            .subscriptions
            .remove_table_subscription::<D>(subscription);
    }

    /// Subscribe to a specific key in the table.
    pub fn subscribe_key(
        &self,
        subscriber: crate::Subscriber,
        key: D::Key,
    ) -> Result<crate::Subscription>
    where
        D::Key: Send,
    {
        let subs = &self.read_lock().subscriptions;
        let id = subs.create_table_subscription::<D>(key, subscriber)?;
        Ok(id)
    }

    /// Subscribe to a specific key in the table and send the current value (if any) to the subscriber.
    pub fn subscribe_key_and_notify(
        &self,
        subscriber: crate::Subscriber,
        key: D::Key,
    ) -> Result<crate::Subscription>
    where
        D::Key: Send,
    {
        let storage = self.read_lock();
        let subs = &storage.subscriptions;
        let id = subs.create_table_subscription::<D>(key.clone(), subscriber)?;

        crate::pub_sub::send_current::<D>(subs, &storage, key, id);

        Ok(id)
    }
}

#[cfg(test)]
mod test {
    use std::sync::Arc;

    use crate::{KvErrorExt, store};

    store!(
        kvs: {
            Count(u64; OWNER),
            Shared(Arc<String>; OWNER),
            Label(&'static u64; OWNER),
            Boxed(Box<String>; OWNER),
        }
        tables: {
            Items(&'static str => String; OWNER),
            Counters(u32 => u64; OWNER),
        }
    );

    const OWNER: &str = "owner";
    const OTHER: &str = "other";

    #[test]
    fn get_returns_none_when_absent() {
        let store = KvStore::new();
        assert!(store.Count.get(OWNER).is_none());
    }

    #[test]
    fn get_returns_value_after_insert() {
        let store = KvStore::new();
        store.Count.insert(OWNER, 42);
        assert_eq!(store.Count.get(OWNER), Some(42));
    }

    #[test]
    fn get_ref_singleton() {
        static STATIC_LABEL: u64 = 99;
        let store = KvStore::new();
        store.Label.insert(OWNER, &STATIC_LABEL);
        assert_eq!(store.Label.get(OWNER), Some(&99));
    }

    #[test]
    fn with_returns_none_and_does_not_call_f_when_absent() {
        let store = KvStore::new();
        let mut called = false;
        let result = store.Count.with(OWNER, |_| {
            called = true;
        });
        assert!(result.is_none());
        assert!(!called);
    }

    #[test]
    fn with_returns_result_of_f() {
        let store = KvStore::new();
        store.Count.insert(OWNER, 5);
        assert_eq!(store.Count.with(OWNER, |v| v * 2), Some(10));
    }

    #[test]
    fn get_arc_singleton_shares_allocation() {
        let store = KvStore::new();
        let arc = Arc::new("hello".to_owned());
        store.Shared.insert(OWNER, arc.clone());
        let got = store.Shared.get(OWNER).unwrap();
        assert_eq!(*got, "hello");
        // `get` clones the `Arc` rather than the pointee.
        assert!(Arc::ptr_eq(&arc, &got));
    }

    #[test]
    fn with_mut_returns_none_and_does_not_call_f_when_absent() {
        let store = KvStore::new();
        let mut called = false;
        let result = store.Count.with_mut(OWNER, |_| {
            called = true;
        });
        assert!(result.is_none());
        assert!(!called);
    }

    #[test]
    fn with_mut_does_not_insert_when_absent() {
        let store = KvStore::new();
        store.Count.with_mut(OWNER, |v| *v = 7);
        assert!(store.Count.get(OWNER).is_none());
    }

    #[test]
    fn with_mut_passes_current_value() {
        let store = KvStore::new();
        store.Count.insert(OWNER, 5);
        let mut seen = None;
        store.Count.with_mut(OWNER, |v| seen = Some(*v));
        assert_eq!(seen, Some(5));
    }

    #[test]
    fn with_mut_returns_result_of_f() {
        let store = KvStore::new();
        store.Count.insert(OWNER, 5);
        assert_eq!(store.Count.with_mut(OWNER, |v| *v * 2), Some(10));
    }

    #[test]
    fn with_mut_mutates_existing_value() {
        let store = KvStore::new();
        store.Count.insert(OWNER, 5);
        store.Count.with_mut(OWNER, |v| *v *= 2);
        assert_eq!(store.Count.get(OWNER), Some(10));
    }

    #[test]
    fn with_mut_sees_previous_with_mut() {
        let store = KvStore::new();
        store.Count.insert(OWNER, 0);
        store.Count.with_mut(OWNER, |v| *v += 1);
        store.Count.with_mut(OWNER, |v| *v += 1);
        store.Count.with_mut(OWNER, |v| *v += 1);
        assert_eq!(store.Count.get(OWNER), Some(3));
    }

    #[test]
    fn with_mut_returns_none_after_remove() {
        let store = KvStore::new();
        store.Count.insert(OWNER, 5);
        store.Count.remove(OWNER);
        let mut called = false;
        let result = store.Count.with_mut(OWNER, |_| called = true);
        assert!(result.is_none());
        assert!(!called);
        assert!(store.Count.get(OWNER).is_none());
    }

    #[test]
    fn with_mut_box_singleton() {
        let store = KvStore::new();
        store.Boxed.insert(OWNER, Box::new("hello".to_owned()));
        store.Boxed.with_mut(OWNER, |v| v.push('!'));
        assert_eq!(store.Boxed.get(OWNER), Some(Box::new("hello!".to_owned())));
    }

    #[test]
    fn with_mut_arc_singleton() {
        let store = KvStore::new();
        store.Shared.insert(OWNER, Arc::new("hello".to_owned()));
        store
            .Shared
            .with_mut(OWNER, |v| *v = Arc::new(format!("{v}!")));
        assert_eq!(
            store.Shared.get(OWNER).as_deref(),
            Some(&"hello!".to_owned())
        );
    }

    #[test]
    fn with_mut_ref_singleton() {
        static OLD_LABEL: u64 = 1;
        static NEW_LABEL: u64 = 2;
        let store = KvStore::new();
        store.Label.insert(OWNER, &OLD_LABEL);
        store.Label.with_mut(OWNER, |v| {
            assert_eq!(**v, 1);
            *v = &NEW_LABEL;
        });
        assert_eq!(store.Label.get(OWNER), Some(&2));
    }

    #[test]
    #[cfg_attr(debug_assertions, should_panic(expected = "Ownership violation"))]
    fn with_mut_wrong_owner_panics() {
        let store = KvStore::new();
        store.Count.insert(OWNER, 1);
        store.Count.with_mut(OTHER, |v| *v = 2);
    }

    #[test]
    fn remove_makes_entry_absent() {
        let store = KvStore::new();
        store.Count.insert(OWNER, 1);
        store.Count.remove(OWNER);
        assert!(store.Count.get(OWNER).is_none());
    }

    #[test]
    #[cfg_attr(debug_assertions, should_panic(expected = "Ownership violation"))]
    fn singleton_insert_wrong_owner_panics() {
        let store = KvStore::new();
        store.Count.insert(OWNER, 1);
        store.Count.insert(OTHER, 2);
    }

    #[test]
    #[cfg_attr(debug_assertions, should_panic(expected = "Ownership violation"))]
    fn singleton_remove_wrong_owner_panics() {
        let store = KvStore::new();
        store.Count.insert(OWNER, 1);
        store.Count.remove(OTHER);
    }

    #[test]
    fn table_get_returns_none_when_absent() {
        let store = KvStore::new();
        assert!(store.Items.get(OWNER, "missing").is_none());
    }

    #[test]
    fn table_get_returns_value_after_insert() {
        let store = KvStore::new();
        store.Items.insert(OWNER, "k", "val".to_owned());
        assert_eq!(store.Items.get(OWNER, "k"), Some("val".to_owned()));
    }

    #[test]
    fn table_get_with_borrow_type() {
        let store = KvStore::new();
        store.Counters.insert(OWNER, 42u32, 100u64);
        assert_eq!(store.Counters.get(OWNER, &42u32), Some(100u64));
    }

    #[test]
    fn table_with_returns_none_and_does_not_call_f_when_absent() {
        let store = KvStore::new();
        let mut called = false;
        let result = store.Items.with(OWNER, "missing", |_| {
            called = true;
        });
        assert!(result.is_none());
        assert!(!called);
    }

    #[test]
    fn table_with_returns_some_after_insert() {
        let store = KvStore::new();
        store.Items.insert(OWNER, "k", "val".to_owned());
        assert_eq!(store.Items.with(OWNER, "k", |s| s.len()), Some(3));
    }

    #[test]
    fn table_mutate_returns_none_when_absent() {
        let store = KvStore::new();
        assert!(
            store
                .Items
                .with_mut(OWNER, &"missing", |v| v.len())
                .is_none()
        );
    }

    #[test]
    fn table_mutate_modifies_value() {
        let store = KvStore::new();
        store.Items.insert(OWNER, "k", "hello".to_owned());
        store.Items.with_mut(OWNER, &"k", |v| v.push('!')).unwrap();
        assert_eq!(store.Items.get(OWNER, "k"), Some("hello!".to_owned()));
    }

    #[test]
    fn table_remove_makes_get_return_none() {
        let store = KvStore::new();
        store.Items.insert(OWNER, "k", "v".to_owned());
        store.Items.remove(OWNER, &"k");
        assert!(store.Items.get(OWNER, "k").is_none());
    }

    #[test]
    fn table_clear_removes_all_rows() {
        let store = KvStore::new();
        let table = &store.Items;
        table.insert(OWNER, "a", "alpha".to_owned());
        table.insert(OWNER, "b", "beta".to_owned());
        table.insert(OWNER, "c", "gamma".to_owned());
        table.clear(OWNER);
        assert!(table.is_empty());
    }

    #[test]
    fn table_clear_preserves_ownership() {
        let store = KvStore::new();
        store.Items.insert(OWNER, "k", "v".to_owned());
        store.Items.clear(OWNER);
        // Same owner can still write after clear
        store.Items.insert(OWNER, "k2", "v2".to_owned());
        assert_eq!(store.Items.get(OWNER, "k2"), Some("v2".to_owned()));
    }

    #[test]
    fn table_is_empty_on_fresh_store() {
        let store = KvStore::new();
        assert!(store.Items.is_empty());
    }

    #[test]
    fn table_len_zero_on_fresh_store() {
        let store = KvStore::new();
        assert_eq!(store.Items.len(), 0);
    }

    #[test]
    fn table_len_increases_with_inserts() {
        let store = KvStore::new();
        let table = &store.Items;
        table.insert(OWNER, "a", "alpha".to_owned());
        table.insert(OWNER, "b", "beta".to_owned());
        table.insert(OWNER, "c", "gamma".to_owned());
        assert_eq!(table.len(), 3);
    }

    #[test]
    fn table_len_decreases_after_remove() {
        let store = KvStore::new();
        let table = &store.Items;
        table.insert(OWNER, "a", "alpha".to_owned());
        table.insert(OWNER, "b", "beta".to_owned());
        table.remove(OWNER, &"a");
        assert_eq!(table.len(), 1);
    }

    #[test]
    fn table_is_empty_false_after_insert() {
        let store = KvStore::new();
        store.Items.insert(OWNER, "k", "v".to_owned());
        assert!(!store.Items.is_empty());
    }

    #[test]
    fn table_iter_empty_on_fresh_store() {
        let store = KvStore::new();
        let table = &store.Items;
        assert_eq!(table.with_iter(OWNER, |i| i.count()), 0);
    }

    #[test]
    fn table_iter_yields_all_rows() {
        let store = KvStore::new();
        let table = &store.Items;
        table.insert(OWNER, "a", "alpha".to_owned());
        table.insert(OWNER, "b", "beta".to_owned());
        let mut items: Vec<_> =
            table.with_iter(OWNER, |i| i.map(|(k, v)| (*k, v.clone())).collect());
        items.sort();
        assert_eq!(
            items,
            vec![("a", "alpha".to_owned()), ("b", "beta".to_owned())]
        );
    }

    #[test]
    fn table_iter_reflects_mutations() {
        let store = KvStore::new();
        let table = &store.Items;
        table.insert(OWNER, "k", "v1".to_owned());
        table
            .with_mut(OWNER, &"k", |v| {
                v.clear();
                v.push_str("v2");
            })
            .unwrap();
        let items: Vec<_> = table.with_iter(OWNER, |i| i.map(|(k, v)| (*k, v.clone())).collect());
        assert_eq!(items, vec![("k", "v2".to_owned())]);
    }

    #[test]
    fn table_for_each_empty_calls_closure_zero_times() {
        let store = KvStore::new();
        let table = &store.Items;
        let mut count = 0;
        table.with_iter(OWNER, |i| i.for_each(|_| count += 1));
        assert_eq!(count, 0);
    }

    #[test]
    fn table_for_each_yields_all_rows() {
        let store = KvStore::new();
        let table = &store.Items;
        table.insert(OWNER, "a", "alpha".to_owned());
        table.insert(OWNER, "b", "beta".to_owned());
        let mut items: Vec<_> = Vec::new();
        table.with_iter(OWNER, |i| i.for_each(|(k, v)| items.push((*k, v.clone()))));
        items.sort();
        assert_eq!(
            items,
            vec![("a", "alpha".to_owned()), ("b", "beta".to_owned())]
        );
    }

    #[test]
    fn table_with_iter_mut_modifies_values() {
        let store = KvStore::new();
        let table = &store.Items;
        table.insert(OWNER, "k", "hello".to_owned());
        table.with_iter_mut(OWNER, |i| i.next().unwrap().1.push('!'));
        assert_eq!(table.get(OWNER, "k"), Some("hello!".to_owned()));
    }

    #[test]
    fn table_with_iter_mut_empty_yields_none() {
        let store = KvStore::new();
        let table = &store.Items;
        let count = table.with_iter_mut(OWNER, |i| i.count());
        assert_eq!(count, 0);
    }

    #[test]
    fn table_with_iter_mut_visits_all_rows() {
        let store = KvStore::new();
        let table = &store.Items;
        table.insert(OWNER, "a", "x".to_owned());
        table.insert(OWNER, "b", "y".to_owned());
        table.insert(OWNER, "c", "z".to_owned());
        table.with_iter_mut(OWNER, |i| {
            for (_, v) in i {
                v.push('!');
            }
        });
        assert_eq!(table.get(OWNER, "a"), Some("x!".to_owned()));
        assert_eq!(table.get(OWNER, "b"), Some("y!".to_owned()));
        assert_eq!(table.get(OWNER, "c"), Some("z!".to_owned()));
    }

    #[test]
    fn table_iter_keys_cloned_empty() {
        let store = KvStore::new();
        let table = &store.Items;
        assert_eq!(table.with_keys(OWNER, |k| k.count()), 0);
    }

    #[test]
    fn table_iter_keys_cloned_yields_all_keys() {
        let store = KvStore::new();
        let table = &store.Items;
        table.insert(OWNER, "a", "alpha".to_owned());
        table.insert(OWNER, "b", "beta".to_owned());
        let mut keys: Vec<_> = table.with_keys(OWNER, |k| k.copied().collect());
        keys.sort();
        assert_eq!(keys, vec!["a", "b"]);
    }

    #[test]
    fn table_iter_values_cloned_empty() {
        let store = KvStore::new();
        let table = &store.Items;
        assert_eq!(table.with_values(OWNER, |v| v.count()), 0);
    }

    #[test]
    fn table_iter_values_cloned_yields_all_values() {
        let store = KvStore::new();
        let table = &store.Items;
        table.insert(OWNER, "a", "alpha".to_owned());
        table.insert(OWNER, "b", "beta".to_owned());
        let mut values: Vec<_> = table.with_values(OWNER, |v| v.cloned().collect());
        values.sort();
        assert_eq!(values, vec!["alpha", "beta"]);
    }

    #[test]
    #[cfg(debug_assertions)]
    #[should_panic(expected = "Ownership violation")]
    fn table_insert_wrong_owner_panics() {
        let store = KvStore::new();
        store.Items.insert(OTHER, "k", "v".to_owned());
    }

    #[test]
    #[cfg_attr(debug_assertions, should_panic(expected = "Ownership violation"))]
    fn table_mutate_wrong_owner_panics() {
        let store = KvStore::new();
        store.Items.with_mut(OTHER, &"k", |v| v.len()).unwrap_err();
    }

    #[test]
    #[cfg_attr(debug_assertions, should_panic(expected = "Ownership violation"))]
    fn table_remove_wrong_owner_panics() {
        let store = KvStore::new();
        store.Items.remove(OTHER, &"k");
    }

    #[test]
    #[cfg_attr(debug_assertions, should_panic(expected = "Ownership violation"))]
    fn table_clear_wrong_owner_panics() {
        let store = KvStore::new();
        store.Items.clear(OTHER);
    }

    #[test]
    fn table_remove_used_in_statement_position() {
        let store = KvStore::new();
        store.Items.insert(OWNER, "k", "v".to_owned());
        store.Items.remove(OWNER, &"k");
        assert_eq!(store.Items.get(OWNER, "k"), None);
    }

    #[test]
    fn with_owner_singleton_round_trip() {
        let store = KvStore::new();
        let owned = store.with_owner(OWNER);

        owned.Count.insert(5);
        assert_eq!(owned.Count.get(), Some(5));
        assert_eq!(owned.Count.with(|v| v * 2), Some(10));
        assert_eq!(owned.Count.with_mut(|v| *v += 1), Some(()));
        assert_eq!(owned.Count.get(), Some(6));

        owned.Count.remove();
        assert!(owned.Count.get().is_none());
    }

    #[test]
    fn with_owner_table_round_trip() {
        let store = KvStore::new();
        let owned = store.with_owner(OWNER);

        owned.Items.insert("a", "alpha".to_owned());
        owned.Items.insert("b", "beta".to_owned());
        assert_eq!(owned.Items.get("a"), Some("alpha".to_owned()));
        assert_eq!(owned.Items.with("a", |v| v.len()), Some(5));
        assert_eq!(owned.Items.len(), 2);
        assert!(!owned.Items.is_empty());

        owned.Items.with_mut(&"a", |v| v.push('!')).unwrap();
        assert_eq!(owned.Items.get("a"), Some("alpha!".to_owned()));

        let mut keys: Vec<_> = owned.Items.with_keys(|k| k.copied().collect());
        keys.sort();
        assert_eq!(keys, vec!["a", "b"]);
        assert_eq!(owned.Items.with_iter(|i| i.count()), 2);
        assert_eq!(owned.Items.with_values(|v| v.count()), 2);

        owned.Items.with_iter_mut(|i| {
            for (_, v) in i {
                v.push('?');
            }
        });
        assert_eq!(owned.Items.get("b"), Some("beta?".to_owned()));

        owned.Items.remove(&"a");
        assert_eq!(owned.Items.len(), 1);
        owned.Items.clear();
        assert!(owned.Items.is_empty());
    }

    #[test]
    fn with_owner_writes_visible_to_the_store() {
        let store = KvStore::new();
        {
            let owned = store.with_owner(OWNER);
            owned.Count.insert(7);
            owned.Items.insert("k", "v".to_owned());
        }
        assert_eq!(store.Count.get(OWNER), Some(7));
        assert_eq!(store.Items.get(OWNER, "k"), Some("v".to_owned()));
    }

    #[test]
    fn with_owner_transaction_uses_the_owner() {
        let store = KvStore::new();
        let owned = store.with_owner(OWNER);

        let mut txn = owned.begin_transaction();
        txn.Count.insert(1);
        txn.Items.insert("k", "v".to_owned());
        txn.commit().unwrap();

        assert_eq!(owned.Count.get(), Some(1));

        let txn = owned.begin_ro_transaction();
        assert_eq!(txn.Items.get("k"), Some("v".to_owned()));
    }

    #[test]
    #[cfg(debug_assertions)]
    #[should_panic(expected = "Ownership violation")]
    fn with_owner_wrong_owner_panics() {
        let store = KvStore::new();
        store.Count.insert(OWNER, 1);
        store.with_owner(OTHER).Count.insert(2);
    }

    #[test]
    fn swapped_store_fields_stay_valid() {
        let mut a = KvStore::new();
        let mut b = KvStore::new();
        std::mem::swap(&mut a.Items, &mut b.Items);
        drop(b);
        // `a.Items` now accesses `b`'s store, which must still be alive.
        a.Items.insert(OWNER, "k", "v".to_owned());
        assert_eq!(a.Items.get(OWNER, "k"), Some("v".to_owned()));
        assert!(a.begin_ro_transaction(OWNER).Items.get(&"k").is_none());
    }
}
