//! KvStore non-transactional API.

use std::{borrow::Borrow, hash::Hash, marker::PhantomData};

use crate::{
    Error, KvStore, Owner, Result, SingletonTransaction, TableTransaction,
    operations::{Ops, SingletonOps, SingletonOpsMut, StorageGuard, TabularOps, TabularOpsMut},
    schema,
    storage::Storage,
    transactions::SchemaTransaction,
};

/// Access singleton data in the store.
///
/// `S` describes the data and instances are generated by the schema macros.
pub struct Singleton<
    TableStorage: schema::GeneratedStorage + 'static,
    S: schema::SingletonDesc<Storage = TableStorage>,
> {
    /// Invariant: the store outlives `self`.
    store: *const KvStore<TableStorage>,
    desc: PhantomData<S>,
}

// SAFETY: by the field invariant of `store`.
unsafe impl<
    TableStorage: schema::GeneratedStorage + 'static,
    S: schema::SingletonDesc<Storage = TableStorage>,
> Send for Singleton<TableStorage, S>
{
}
// SAFETY: by the field invariant of `store` and because `KvStore` is `Sync`.
unsafe impl<
    TableStorage: schema::GeneratedStorage + 'static,
    S: schema::SingletonDesc<Storage = TableStorage>,
> Sync for Singleton<TableStorage, S>
{
}

impl<
    TableStorage: schema::GeneratedStorage + 'static,
    S: schema::SingletonDesc<Storage = TableStorage>,
> Singleton<TableStorage, S>
{
    /// SAFETY: the caller must ensure that the target of `store` will outlive `self`.
    #[doc(hidden)]
    pub unsafe fn new(store: *const KvStore<TableStorage>) -> Self {
        Singleton {
            store,
            desc: PhantomData,
        }
    }

    fn store(&self) -> &KvStore<TableStorage> {
        // SAFETY: safe since `self.store` must be live since `self` is (by it's field invariant).
        unsafe { &(*self.store) }
    }

    /// Subscribe to a singleton key-value pair.
    pub fn subscribe(
        &self,
        subscriber: impl Into<crate::Subscriber>,
    ) -> Result<crate::Subscription> {
        let subs = &self.read_lock().subscriptions;
        let id = subs.create_singleton_subscription::<S>(subscriber.into())?;

        Ok(id)
    }

    /// Subscribe to a singleton key-value pair and send the current value (if any) to the subscriber.
    pub fn subscribe_and_notify(
        &self,
        subscriber: impl Into<crate::Subscriber>,
    ) -> Result<crate::Subscription> {
        let storage = self.read_lock();
        let subs = &storage.subscriptions;
        let id = subs.create_singleton_subscription::<S>(subscriber.into())?;

        crate::pub_sub::send_current_singleton::<S>(subs, storage.storage(), id);

        Ok(id)
    }

    /// Unsubscribe to a singleton key-value pair.
    pub fn unsubscribe(&self, subscription: crate::Subscription) {
        self.read_lock()
            .subscriptions
            .remove_singleton_subscription::<S>(subscription)
    }

    /// Get a single value from the store by cloning the value.
    ///
    /// Returns `None` if there is no value for the specified key.
    pub fn get(&self, owner: Owner) -> Option<S::Value>
    where
        S::Value: Clone,
    {
        <&Self as SingletonOps<_>>::get::<S>(self, owner)
    }

    /// Get immutable access to a value in the store by reference.
    ///
    /// Returns `None` (and does not call `f`) if there is no value for the specified key.
    pub fn with<T>(&self, owner: Owner, f: impl FnOnce(&S::Value) -> T) -> Option<T> {
        <&Self as SingletonOps<_>>::with::<S, T>(self, f, owner)
    }

    /// Get mutable access to a value in the store by reference.
    ///
    /// Returns `None` (and does not call `f`) if there is no value for the specified key.
    pub fn with_mut<T>(&self, owner: Owner, f: impl FnOnce(&mut S::Value) -> T) -> Option<T>
    where
        S::Value: Clone + PartialEq,
    {
        // Should never panic since transaction should only fail on index inserts.
        in_singleton_txn::<_, S, _>(self.store(), owner, |view| {
            SingletonOpsMut::with_mut::<S, T>(view, f, owner)
        })
        .unwrap()
    }

    /// Insert a single value into the store.
    pub fn insert(&self, owner: Owner, value: S::Value) {
        // Should never panic since transaction should only fail on index inserts.
        in_singleton_txn::<_, S, _>(self.store(), owner, |view| {
            SingletonOpsMut::insert::<S>(view, value, owner)
        })
        .unwrap()
    }

    /// Remove a single value from the store.
    pub fn remove(&self, owner: Owner) {
        // Should never panic since transaction should only fail on index inserts.
        in_singleton_txn::<_, S, _>(self.store(), owner, |view| {
            SingletonOpsMut::remove::<S>(view, owner)
        })
        .unwrap()
    }
}

impl<
    'store,
    TableStorage: schema::GeneratedStorage + 'static,
    S: schema::SingletonDesc<Storage = TableStorage>,
> Ops<TableStorage> for &'store Singleton<TableStorage, S>
{
    type ReadLock = std::sync::RwLockReadGuard<'store, Storage<TableStorage>>;

    fn read_lock(self) -> Self::ReadLock {
        // SAFETY: safe since `self.store` must be live since `self` is (by it's field invariant),
        // and the returned lock carries the `'store` lifetime.
        unsafe { (*self.store).get_read_lock() }
    }
}

impl<
    TableStorage: schema::GeneratedStorage + 'static,
    S: schema::SingletonDesc<Storage = TableStorage>,
> SingletonOps<TableStorage> for &Singleton<TableStorage, S>
{
}

/// Apply `f` to `S`'s view of a transaction which contains only that operation, and commit it.
///
/// Returns the error from committing, if there is one. This is how the non-transactional singleton
/// operations get their atomicity: each one is a single-operation transaction.
fn in_singleton_txn<TableStorage, S, T>(
    store: &KvStore<TableStorage>,
    owner: Owner,
    f: impl FnOnce(&mut SingletonTransaction<'_, TableStorage, S>) -> T,
) -> Result<T>
where
    TableStorage: schema::GeneratedStorage + 'static,
    S: schema::SingletonDesc<Storage = TableStorage>,
{
    let mut txn = store.begin_transaction(owner);
    let result = f(S::make_txn_view(&mut txn));
    txn.commit()?;
    Ok(result)
}

/// Access tabular data in the store.
///
/// `D` describes the table and instances are generated by the schema macros.
pub struct Table<
    TableStorage: schema::GeneratedStorage + 'static,
    D: schema::TableDesc<Storage = TableStorage>,
> {
    /// Invariant: the store outlives `self`.
    store: *const KvStore<TableStorage>,
    desc: PhantomData<D>,
}

// SAFETY: by the field invariant of `store`.
unsafe impl<
    TableStorage: schema::GeneratedStorage + 'static,
    D: schema::TableDesc<Storage = TableStorage>,
> Send for Table<TableStorage, D>
{
}
// SAFETY: by the field invariant of `store` and because `KvStore` is `Sync`.
unsafe impl<
    TableStorage: schema::GeneratedStorage + 'static,
    D: schema::TableDesc<Storage = TableStorage>,
> Sync for Table<TableStorage, D>
{
}

impl<TableStorage: schema::GeneratedStorage + 'static, D: schema::TableDesc<Storage = TableStorage>>
    Table<TableStorage, D>
{
    /// SAFETY: the caller must ensure that the target of `store` will outlive `self`.
    #[doc(hidden)]
    pub unsafe fn new(store: *const KvStore<TableStorage>) -> Self {
        Table {
            store,
            desc: PhantomData,
        }
    }

    fn store(&self) -> &KvStore<TableStorage> {
        // SAFETY: safe since `self.store` must be live since `self` is (by it's field invariant).
        unsafe { &(*self.store) }
    }

    /// The number of key/value pairs in the table.
    pub fn len(&self) -> usize {
        <&Self as TabularOps<_>>::len(self)
    }

    /// True if the table is empty.
    pub fn is_empty(&self) -> bool {
        <&Self as TabularOps<_>>::is_empty(self)
    }

    /// Clear a table by removing all its KVs.
    pub fn clear(&self, owner: Owner) {
        // Should never panic since transaction should only fail on index inserts.
        in_table_txn::<_, D, _>(self.store(), owner, |view| {
            TabularOpsMut::clear(view, owner)
        })
        .unwrap()
    }

    /// Get a row of the table from the store by cloning the value.
    ///
    /// Returns `None` if there is no value for the specified key.
    pub fn get<Q>(&self, owner: Owner, key: &Q) -> Option<D::Value>
    where
        D::Value: Clone,
        D::Key: Borrow<Q>,
        Q: ?Sized + Hash + Eq,
    {
        <&Self as TabularOps<_>>::get(self, key, owner)
    }

    /// Get immutable access to a row of the table in the store by reference.
    ///
    /// Returns `None` (and does not call `f`) if there is no value for the specified key.
    pub fn with<Q, T>(&self, owner: Owner, key: &Q, f: impl FnOnce(&D::Value) -> T) -> Option<T>
    where
        D::Key: Borrow<Q>,
        Q: ?Sized + Hash + Eq,
    {
        <&Self as TabularOps<_>>::with(self, key, f, owner)
    }

    /// Insert a `value` into the table.
    ///
    /// Panics if the value is already indexed with the same index key.
    pub fn insert(&self, owner: Owner, key: D::Key, value: D::Value) {
        self.try_insert(owner, key, value).unwrap();
    }

    /// Insert a `value` into the table.
    ///
    /// Returns an error if `insert` would panic.
    pub fn try_insert(&self, owner: Owner, key: D::Key, value: D::Value) -> Result<()> {
        in_table_txn::<_, D, _>(self.store(), owner, |view| {
            TabularOpsMut::insert(view, key, value, owner)
        })
    }

    /// Get mutable access to a row of the table in the store in the store.
    ///
    /// Returns `Error::NotPresent` (and does not call `f`) if there is no value for the specified key.
    pub fn with_mut<Q, T>(
        &self,
        owner: Owner,
        key: &Q,
        f: impl FnOnce(&mut D::Value) -> T,
    ) -> Result<T>
    where
        D::Key: Borrow<Q>,
        Q: ?Sized + Hash + Eq + ToOwned<Owned = D::Key>,
        D::Value: Clone + PartialEq,
    {
        in_table_txn::<_, D, _>(self.store(), owner, |view| {
            TabularOpsMut::with_mut(view, key, f, owner)
        })?
        .ok_or(Error::NotPresent)
    }

    /// Remove a row from the table.
    pub fn remove<Q>(&self, owner: Owner, key: &Q)
    where
        D::Key: Borrow<Q>,
        Q: ?Sized + Hash + Eq + ToOwned<Owned = D::Key>,
    {
        // Should never panic since transaction should only fail on index inserts.
        in_table_txn::<_, D, _>(self.store(), owner, |view| {
            TabularOpsMut::remove(view, key, owner)
        })
        .unwrap()
    }

    /// Iterate all the key/value pairs in a table.
    pub fn iter(&self, owner: Owner) -> impl Iterator<Item = (&D::Key, &D::Value)> {
        <&Self as TabularOps<_>>::iter(self, owner)
    }

    /// Iterate all the keys in a table.
    pub fn keys(&self, owner: Owner) -> impl Iterator<Item = &D::Key> {
        <&Self as TabularOps<_>>::keys(self, owner)
    }

    /// Iterate all the values in a table.
    pub fn values(&self, owner: Owner) -> impl Iterator<Item = &D::Value> {
        <&Self as TabularOps<_>>::values(self, owner)
    }

    /// Iterate all the key/value pairs in a table.
    ///
    /// If you need a mutable iterator without access scoped by a closure, use `iter_mut` within a
    /// transaction.
    pub fn with_iter_mut<F, T>(&self, owner: Owner, mut f: F) -> T
    where
        F: for<'a> FnMut(&mut dyn Iterator<Item = (&'a D::Key, &'a mut D::Value)>) -> T,
        D::Value: Clone + PartialEq,
    {
        // Should never panic since transaction should only fail on index inserts.
        in_table_txn::<_, D, _>(self.store(), owner, |view| {
            let mut iter = TabularOpsMut::iter_mut(view, owner);
            f(&mut iter)
        })
        .unwrap()
    }
}

impl<TableStorage: schema::GeneratedStorage + 'static, D: schema::Indexable<Storage = TableStorage>>
    Table<TableStorage, D>
{
    /// Access the table via its indexes.
    ///
    /// Returns a macro-generated struct with a field for each index declared for the table; each
    /// field is an [`Index`](crate::Index) which gives access to the table using that index's key.
    ///
    /// # Example:
    ///
    /// ```rust,ignore
    /// let value = store.Foo.indexes().bar.get(OWNER, key).unwrap();
    /// ```
    ///
    /// Here `Foo` is a table and `bar` is an index over `Foo` using the `bar` field as foreign key.
    pub fn indexes(&self) -> D::Indexes<'_> {
        self.store().into()
    }
}

impl<
    TableStorage: schema::GeneratedStorage + 'static,
    D: schema::Notifiable<Storage = TableStorage>,
> Table<TableStorage, D>
{
    /// Subscribe to the whole table.
    pub fn subscribe(&self, subscriber: impl Into<crate::Subscriber>) -> Result<crate::Subscription>
    where
        D::Key: Send,
    {
        let subs = &self.store().get_read_lock().subscriptions;
        let id = subs.create_table_subscription_all::<D>(subscriber.into())?;
        Ok(id)
    }

    /// Unsubscribe from the table (whole table or single key).
    pub fn unsubscribe(&self, subscription: crate::Subscription) {
        self.store()
            .get_read_lock()
            .subscriptions
            .remove_table_subscription::<D>(subscription);
    }

    /// Subscribe to a specific key in the table.
    pub fn subscribe_key(
        &self,
        subscriber: impl Into<crate::Subscriber>,
        key: D::Key,
    ) -> Result<crate::Subscription>
    where
        D::Key: Send,
    {
        let subs = &self.store().get_read_lock().subscriptions;
        let id = subs.create_table_subscription::<D>(key, subscriber.into())?;
        Ok(id)
    }

    /// Subscribe to a specific key in the table and send the current value (if any) to the subscriber.
    pub fn subscribe_key_and_notify(
        &self,
        subscriber: impl Into<crate::Subscriber>,
        key: D::Key,
    ) -> Result<crate::Subscription>
    where
        D::Key: Send,
    {
        let storage = self.store().get_read_lock();
        let subs = &storage.subscriptions;
        let id = subs.create_table_subscription::<D>(key.clone(), subscriber.into())?;

        crate::pub_sub::send_current::<D>(subs, storage.storage(), key, id);

        Ok(id)
    }
}

impl<
    'store,
    TableStorage: schema::GeneratedStorage + 'static,
    D: schema::TableDesc<Storage = TableStorage>,
> Ops<TableStorage> for &'store Table<TableStorage, D>
{
    type ReadLock = std::sync::RwLockReadGuard<'store, Storage<TableStorage>>;

    fn read_lock(self) -> Self::ReadLock {
        // SAFETY: safe since `self.store` must be live since `self` is (by it's field invariant),
        // and the returned lock carries the `'store` lifetime.
        unsafe { (*self.store).get_read_lock() }
    }
}

impl<TableStorage: schema::GeneratedStorage + 'static, D: schema::TableDesc<Storage = TableStorage>>
    TabularOps<TableStorage> for &Table<TableStorage, D>
{
    type TableDesc = D;
}

/// Apply `f` to `D`'s view of a transaction which contains only that operation, and commit it.
///
/// Returns the error from committing, if there is one. This is how the non-transactional table
/// operations get their atomicity: each one is a single-operation transaction.
fn in_table_txn<TableStorage, D, T>(
    store: &KvStore<TableStorage>,
    owner: Owner,
    f: impl FnOnce(&mut TableTransaction<'_, TableStorage, D>) -> T,
) -> Result<T>
where
    TableStorage: schema::GeneratedStorage + 'static,
    D: schema::TableDesc<Storage = TableStorage>,
{
    let mut txn = store.begin_transaction(owner);
    let result = f(D::make_txn_view(&mut txn));
    txn.commit()?;
    Ok(result)
}

/// A singleton in the store, accessed with a fixed owner.
///
/// The owner-carrying counterpart of [`Singleton`]: the operations are the same, but the owner is
/// supplied once (by the generated `StoreWithOwner`) rather than on each call. There is a field of this type in
/// the generated `StoreWithOwner` for each singleton in the schema.
pub struct SingletonWithOwner<
    'store,
    TableStorage: schema::GeneratedStorage + 'static,
    S: schema::SingletonDesc<Storage = TableStorage>,
> {
    store: &'store KvStore<TableStorage>,
    owner: Owner,
    desc: PhantomData<S>,
}

impl<
    'store,
    TableStorage: schema::GeneratedStorage + 'static,
    S: schema::SingletonDesc<Storage = TableStorage>,
> SingletonWithOwner<'store, TableStorage, S>
{
    #[doc(hidden)]
    pub fn new(store: &'store KvStore<TableStorage>, owner: Owner) -> Self {
        SingletonWithOwner {
            store,
            owner,
            desc: PhantomData,
        }
    }

    /// Subscribe to a singleton key-value pair.
    pub fn subscribe(&self, subscriber: crate::Subscriber) -> Result<crate::Subscription> {
        let subs = &self.read_lock().subscriptions;
        let id = subs.create_singleton_subscription::<S>(subscriber)?;

        Ok(id)
    }

    /// Subscribe to a singleton key-value pair and send the current value (if any) to the subscriber.
    pub fn subscribe_and_notify(
        &self,
        subscriber: crate::Subscriber,
    ) -> Result<crate::Subscription> {
        let storage = self.read_lock();
        let subs = &storage.subscriptions;
        let id = subs.create_singleton_subscription::<S>(subscriber)?;

        crate::pub_sub::send_current_singleton::<S>(subs, storage.storage(), id);

        Ok(id)
    }

    /// Unsubscribe to a singleton key-value pair.
    pub fn unsubscribe(&self, subscription: crate::Subscription) {
        self.read_lock()
            .subscriptions
            .remove_singleton_subscription::<S>(subscription)
    }

    /// Get a single value from the store by cloning the value.
    ///
    /// Returns `None` if there is no value for the specified key.
    pub fn get(&self) -> Option<S::Value>
    where
        S::Value: Clone,
    {
        <&Self as SingletonOps<_>>::get::<S>(self, self.owner)
    }

    /// Get immutable access to a value in the store by reference.
    ///
    /// Returns `None` (and does not call `f`) if there is no value for the specified key.
    pub fn with<T>(&self, f: impl FnOnce(&S::Value) -> T) -> Option<T> {
        <&Self as SingletonOps<_>>::with::<S, T>(self, f, self.owner)
    }

    /// Get mutable access to a value in the store by reference.
    ///
    /// Returns `None` (and does not call `f`) if there is no value for the specified key.
    pub fn with_mut<T>(&self, f: impl FnOnce(&mut S::Value) -> T) -> Option<T>
    where
        S::Value: Clone + PartialEq,
    {
        // Should never panic since transaction should only fail on index inserts.
        in_singleton_txn::<_, S, _>(self.store, self.owner, |view| {
            SingletonOpsMut::with_mut::<S, T>(view, f, self.owner)
        })
        .unwrap()
    }

    /// Insert a single value into the store.
    pub fn insert(&self, value: S::Value) {
        // Should never panic since transaction should only fail on index inserts.
        in_singleton_txn::<_, S, _>(self.store, self.owner, |view| {
            SingletonOpsMut::insert::<S>(view, value, self.owner)
        })
        .unwrap()
    }

    /// Remove a single value from the store.
    pub fn remove(&self) {
        // Should never panic since transaction should only fail on index inserts.
        in_singleton_txn::<_, S, _>(self.store, self.owner, |view| {
            SingletonOpsMut::remove::<S>(view, self.owner)
        })
        .unwrap()
    }
}

impl<
    'store,
    TableStorage: schema::GeneratedStorage + 'static,
    S: schema::SingletonDesc<Storage = TableStorage>,
> Ops<TableStorage> for &SingletonWithOwner<'store, TableStorage, S>
{
    type ReadLock = std::sync::RwLockReadGuard<'store, Storage<TableStorage>>;

    fn read_lock(self) -> Self::ReadLock {
        self.store.get_read_lock()
    }
}

impl<
    TableStorage: schema::GeneratedStorage + 'static,
    S: schema::SingletonDesc<Storage = TableStorage>,
> SingletonOps<TableStorage> for &SingletonWithOwner<'_, TableStorage, S>
{
}

/// A table of key/value pairs in the store, accessed with a fixed owner.
///
/// The owner-carrying counterpart of [`Table`]: the operations are the same, but the owner is
/// supplied once (by the generated `KvStoreWithOwner`) rather than on each call. There is a field of this type in
/// the generated `KvStoreWithOwner` for each table in the schema.
pub struct TableWithOwner<
    'store,
    TableStorage: schema::GeneratedStorage + 'static,
    D: schema::TableDesc<Storage = TableStorage>,
> {
    store: &'store KvStore<TableStorage>,
    owner: Owner,
    desc: PhantomData<D>,
}

impl<
    'store,
    TableStorage: schema::GeneratedStorage + 'static,
    D: schema::TableDesc<Storage = TableStorage>,
> TableWithOwner<'store, TableStorage, D>
{
    #[doc(hidden)]
    pub fn new(store: &'store KvStore<TableStorage>, owner: Owner) -> Self {
        TableWithOwner {
            store,
            owner,
            desc: PhantomData,
        }
    }

    /// The number of key/value pairs in the table.
    pub fn len(&self) -> usize {
        <&Self as TabularOps<_>>::len(self)
    }

    /// True if the table is empty.
    pub fn is_empty(&self) -> bool {
        <&Self as TabularOps<_>>::is_empty(self)
    }

    /// Clear a table by removing all its KVs.
    pub fn clear(&self) {
        // Should never panic since transaction should only fail on index inserts.
        in_table_txn::<_, D, _>(self.store, self.owner, |view| {
            TabularOpsMut::clear(view, self.owner)
        })
        .unwrap()
    }

    /// Get a row of the table from the store by cloning the value.
    ///
    /// Returns `None` if there is no value for the specified key.
    pub fn get<Q>(&self, key: &Q) -> Option<D::Value>
    where
        D::Value: Clone,
        D::Key: Borrow<Q>,
        Q: ?Sized + Hash + Eq,
    {
        <&Self as TabularOps<_>>::get(self, key, self.owner)
    }

    /// Get immutable access to a row of the table in the store by reference.
    ///
    /// Returns `None` (and does not call `f`) if there is no value for the specified key.
    pub fn with<Q, T>(&self, key: &Q, f: impl FnOnce(&D::Value) -> T) -> Option<T>
    where
        D::Key: Borrow<Q>,
        Q: ?Sized + Hash + Eq,
    {
        <&Self as TabularOps<_>>::with(self, key, f, self.owner)
    }

    /// Insert a `value` into the table.
    ///
    /// Panics if the value is already indexed with the same index key.
    pub fn insert(&self, key: D::Key, value: D::Value) {
        self.try_insert(key, value).unwrap();
    }

    /// Insert a `value` into the table.
    ///
    /// Returns an error if `insert` would panic.
    pub fn try_insert(&self, key: D::Key, value: D::Value) -> Result<()> {
        in_table_txn::<_, D, _>(self.store, self.owner, |view| {
            TabularOpsMut::insert(view, key, value, self.owner)
        })
    }

    /// Get mutable access to a row of the table in the store in the store.
    ///
    /// Returns `Error::NotPresent` (and does not call `f`) if there is no value for the specified key.
    pub fn with_mut<Q, T>(&self, key: &Q, f: impl FnOnce(&mut D::Value) -> T) -> Result<T>
    where
        D::Key: Borrow<Q>,
        Q: ?Sized + Hash + Eq + ToOwned<Owned = D::Key>,
        D::Value: Clone + PartialEq,
    {
        in_table_txn::<_, D, _>(self.store, self.owner, |view| {
            TabularOpsMut::with_mut(view, key, f, self.owner)
        })?
        .ok_or(Error::NotPresent)
    }

    /// Remove a row from the table.
    pub fn remove<Q>(&self, key: &Q)
    where
        D::Key: Borrow<Q>,
        Q: ?Sized + Hash + Eq + ToOwned<Owned = D::Key>,
    {
        // Should never panic since transaction should only fail on index inserts.
        in_table_txn::<_, D, _>(self.store, self.owner, |view| {
            TabularOpsMut::remove(view, key, self.owner)
        })
        .unwrap()
    }

    /// Iterate all the key/value pairs in a table.
    pub fn iter(&self) -> impl Iterator<Item = (&'store D::Key, &'store D::Value)> {
        <&Self as TabularOps<_>>::iter(self, self.owner)
    }

    /// Iterate all the keys in a table.
    pub fn keys(&self) -> impl Iterator<Item = &'store D::Key> {
        <&Self as TabularOps<_>>::keys(self, self.owner)
    }

    /// Iterate all the values in a table.
    pub fn values(&self) -> impl Iterator<Item = &'store D::Value> {
        <&Self as TabularOps<_>>::values(self, self.owner)
    }

    /// Iterate all the key/value pairs in a table.
    ///
    /// If you need a mutable iterator without access scoped by a closure, use `iter_mut` within a
    /// transaction.
    pub fn with_iter_mut<F, T>(&self, mut f: F) -> T
    where
        F: for<'a> FnMut(&mut dyn Iterator<Item = (&'a D::Key, &'a mut D::Value)>) -> T,
        D::Value: Clone + PartialEq,
    {
        // Should never panic since transaction should only fail on index inserts.
        in_table_txn::<_, D, _>(self.store, self.owner, |view| {
            let mut iter = TabularOpsMut::iter_mut(view, self.owner);
            f(&mut iter)
        })
        .unwrap()
    }
}

impl<
    'store,
    TableStorage: schema::GeneratedStorage + 'static,
    D: schema::TableDesc<Storage = TableStorage>,
> Ops<TableStorage> for &TableWithOwner<'store, TableStorage, D>
{
    type ReadLock = std::sync::RwLockReadGuard<'store, Storage<TableStorage>>;

    fn read_lock(self) -> Self::ReadLock {
        self.store.get_read_lock()
    }
}

impl<TableStorage: schema::GeneratedStorage + 'static, D: schema::TableDesc<Storage = TableStorage>>
    TabularOps<TableStorage> for &TableWithOwner<'_, TableStorage, D>
{
    type TableDesc = D;
}

impl<
    'store,
    TableStorage: schema::GeneratedStorage + 'static,
    D: schema::Indexable<Storage = TableStorage>,
> TableWithOwner<'store, TableStorage, D>
{
    /// Access the table via its indexes.
    ///
    /// Returns a macro-generated struct with a field for each index declared for the table; each
    /// field is an [`IndexWithOwner`](crate::IndexWithOwner) which gives access to the table using
    /// that index's key.
    ///
    /// # Example:
    ///
    /// ```rust,ignore
    /// let value = store.with_owner(OWNER).Foo.indexes().bar.get(key).unwrap();
    /// ```
    ///
    /// Here `Foo` is a table and `bar` is an index over `Foo` using the `bar` field as foreign key.
    pub fn indexes(&self) -> D::IndexesWithOwner<'store> {
        (self.store, self.owner).into()
    }
}

impl<
    'store,
    TableStorage: schema::GeneratedStorage + 'static,
    D: schema::Notifiable<Storage = TableStorage>,
> TableWithOwner<'store, TableStorage, D>
{
    /// Subscribe to the whole table.
    pub fn subscribe(&self, subscriber: crate::Subscriber) -> Result<crate::Subscription>
    where
        D::Key: Send,
    {
        let subs = &self.read_lock().subscriptions;
        let id = subs.create_table_subscription_all::<D>(subscriber)?;
        Ok(id)
    }

    /// Unsubscribe from the table (whole table or single key).
    pub fn unsubscribe(&self, subscription: crate::Subscription) {
        self.read_lock()
            .subscriptions
            .remove_table_subscription::<D>(subscription);
    }

    /// Subscribe to a specific key in the table.
    pub fn subscribe_key(
        &self,
        subscriber: crate::Subscriber,
        key: D::Key,
    ) -> Result<crate::Subscription>
    where
        D::Key: Send,
    {
        let subs = &self.read_lock().subscriptions;
        let id = subs.create_table_subscription::<D>(key, subscriber)?;
        Ok(id)
    }

    /// Subscribe to a specific key in the table and send the current value (if any) to the subscriber.
    pub fn subscribe_key_and_notify(
        &self,
        subscriber: crate::Subscriber,
        key: D::Key,
    ) -> Result<crate::Subscription>
    where
        D::Key: Send,
    {
        let storage = self.read_lock();
        let subs = &storage.subscriptions;
        let id = subs.create_table_subscription::<D>(key.clone(), subscriber)?;

        crate::pub_sub::send_current::<D>(subs, storage.storage(), key, id);

        Ok(id)
    }
}

#[cfg(test)]
mod test {
    use std::sync::Arc;

    use crate::{KvErrorExt, store};

    store!(
        kvs: {
            Count(u64; OWNER),
            Shared(Arc<String>; OWNER),
            Label(&'static u64; OWNER),
            Boxed(Box<String>; OWNER),
        }
        tables: {
            Items(&'static str => String; OWNER),
            Counters(u32 => u64; OWNER),
        }
    );

    const OWNER: &str = "owner";
    const OTHER: &str = "other";

    #[test]
    fn get_returns_none_when_absent() {
        let store = KvStore::new();
        assert!(store.get::<Count>(OWNER).is_none());
    }

    #[test]
    fn get_returns_value_after_insert() {
        let store = KvStore::new();
        store.insert::<Count>(OWNER, 42);
        assert_eq!(store.get::<Count>(OWNER), Some(42));
    }

    #[test]
    fn get_returns_none_after_remove() {
        let store = KvStore::new();
        store.insert::<Count>(OWNER, 1);
        store.remove::<Count>(OWNER);
        assert!(store.get::<Count>(OWNER).is_none());
    }

    #[test]
    fn get_ref_singleton() {
        static STATIC_LABEL: u64 = 99;
        let store = KvStore::new();
        store.insert::<Label>(OWNER, &STATIC_LABEL);
        assert_eq!(store.get::<Label>(OWNER), Some(&99));
    }

    #[test]
    fn with_returns_none_and_does_not_call_f_when_absent() {
        let store = KvStore::new();
        let mut called = false;
        let result = store.with::<Count, ()>(OWNER, |_| {
            called = true;
        });
        assert!(result.is_none());
        assert!(!called);
    }

    #[test]
    fn with_returns_result_of_f() {
        let store = KvStore::new();
        store.insert::<Count>(OWNER, 5);
        assert_eq!(store.with::<Count, _>(OWNER, |v| v * 2), Some(10));
    }

    #[test]
    fn get_arc_singleton_shares_allocation() {
        let store = KvStore::new();
        let arc = Arc::new("hello".to_owned());
        store.insert::<Shared>(OWNER, arc.clone());
        let got = store.get::<Shared>(OWNER).unwrap();
        assert_eq!(*got, "hello");
        // `get` clones the `Arc` rather than the pointee.
        assert!(Arc::ptr_eq(&arc, &got));
    }

    #[test]
    fn with_mut_returns_none_and_does_not_call_f_when_absent() {
        let store = KvStore::new();
        let mut called = false;
        let result = store.with_mut::<Count, ()>(OWNER, |_| {
            called = true;
        });
        assert!(result.is_none());
        assert!(!called);
    }

    #[test]
    fn with_mut_does_not_insert_when_absent() {
        let store = KvStore::new();
        store.with_mut::<Count, _>(OWNER, |v| *v = 7);
        assert!(store.get::<Count>(OWNER).is_none());
    }

    #[test]
    fn with_mut_passes_current_value() {
        let store = KvStore::new();
        store.insert::<Count>(OWNER, 5);
        let mut seen = None;
        store.with_mut::<Count, _>(OWNER, |v| seen = Some(*v));
        assert_eq!(seen, Some(5));
    }

    #[test]
    fn with_mut_returns_result_of_f() {
        let store = KvStore::new();
        store.insert::<Count>(OWNER, 5);
        assert_eq!(store.with_mut::<Count, _>(OWNER, |v| *v * 2), Some(10));
    }

    #[test]
    fn with_mut_mutates_existing_value() {
        let store = KvStore::new();
        store.insert::<Count>(OWNER, 5);
        store.with_mut::<Count, _>(OWNER, |v| *v *= 2);
        assert_eq!(store.get::<Count>(OWNER), Some(10));
    }

    #[test]
    fn with_mut_sees_previous_with_mut() {
        let store = KvStore::new();
        store.insert::<Count>(OWNER, 0);
        store.with_mut::<Count, _>(OWNER, |v| *v += 1);
        store.with_mut::<Count, _>(OWNER, |v| *v += 1);
        store.with_mut::<Count, _>(OWNER, |v| *v += 1);
        assert_eq!(store.get::<Count>(OWNER), Some(3));
    }

    #[test]
    fn with_mut_returns_none_after_remove() {
        let store = KvStore::new();
        store.insert::<Count>(OWNER, 5);
        store.remove::<Count>(OWNER);
        let mut called = false;
        let result = store.with_mut::<Count, ()>(OWNER, |_| called = true);
        assert!(result.is_none());
        assert!(!called);
        assert!(store.get::<Count>(OWNER).is_none());
    }

    #[test]
    fn with_mut_box_singleton() {
        let store = KvStore::new();
        store.insert::<Boxed>(OWNER, Box::new("hello".to_owned()));
        store.with_mut::<Boxed, _>(OWNER, |v| v.push('!'));
        assert_eq!(
            store.get::<Boxed>(OWNER),
            Some(Box::new("hello!".to_owned()))
        );
    }

    #[test]
    fn with_mut_arc_singleton() {
        let store = KvStore::new();
        store.insert::<Shared>(OWNER, Arc::new("hello".to_owned()));
        store.with_mut::<Shared, _>(OWNER, |v| *v = Arc::new(format!("{v}!")));
        assert_eq!(
            store.get::<Shared>(OWNER).as_deref(),
            Some(&"hello!".to_owned())
        );
    }

    #[test]
    fn with_mut_ref_singleton() {
        static OLD_LABEL: u64 = 1;
        static NEW_LABEL: u64 = 2;
        let store = KvStore::new();
        store.insert::<Label>(OWNER, &OLD_LABEL);
        store.with_mut::<Label, _>(OWNER, |v| {
            assert_eq!(**v, 1);
            *v = &NEW_LABEL;
        });
        assert_eq!(store.get::<Label>(OWNER), Some(&2));
    }

    #[test]
    #[cfg_attr(debug_assertions, should_panic(expected = "Ownership violation"))]
    fn with_mut_wrong_owner_panics() {
        let store = KvStore::new();
        store.insert::<Count>(OWNER, 1);
        store.with_mut::<Count, _>(OTHER, |v| *v = 2);
    }

    #[test]
    fn remove_makes_entry_absent() {
        let store = KvStore::new();
        store.insert::<Count>(OWNER, 1);
        store.remove::<Count>(OWNER);
        assert!(store.get::<Count>(OWNER).is_none());
    }

    #[test]
    #[cfg_attr(debug_assertions, should_panic(expected = "Ownership violation"))]
    fn singleton_insert_wrong_owner_panics() {
        let store = KvStore::new();
        store.insert::<Count>(OWNER, 1);
        store.insert::<Count>(OTHER, 2);
    }

    #[test]
    #[cfg_attr(debug_assertions, should_panic(expected = "Ownership violation"))]
    fn singleton_remove_wrong_owner_panics() {
        let store = KvStore::new();
        store.insert::<Count>(OWNER, 1);
        store.remove::<Count>(OTHER);
    }

    #[test]
    fn table_get_returns_none_when_absent() {
        let store = KvStore::new();
        assert!(store.table::<Items>(OWNER).get("missing").is_none());
    }

    #[test]
    fn table_get_returns_value_after_insert() {
        let store = KvStore::new();
        store.table::<Items>(OWNER).insert("k", "val".to_owned());
        assert_eq!(store.table::<Items>(OWNER).get("k"), Some("val".to_owned()));
    }

    #[test]
    fn table_get_with_borrow_type() {
        let store = KvStore::new();
        store.table::<Counters>(OWNER).insert(42u32, 100u64);
        assert_eq!(store.table::<Counters>(OWNER).get(&42u32), Some(100u64));
    }

    #[test]
    fn table_with_returns_none_and_does_not_call_f_when_absent() {
        let store = KvStore::new();
        let mut called = false;
        let result = store.table::<Items>(OWNER).with("missing", |_| {
            called = true;
        });
        assert!(result.is_none());
        assert!(!called);
    }

    #[test]
    fn table_with_returns_some_after_insert() {
        let store = KvStore::new();
        store.table::<Items>(OWNER).insert("k", "val".to_owned());
        assert_eq!(store.table::<Items>(OWNER).with("k", |s| s.len()), Some(3));
    }

    #[test]
    fn table_mutate_returns_none_when_absent() {
        let store = KvStore::new();
        assert!(
            store
                .table::<Items>(OWNER)
                .with_mut(&"missing", |v| v.len())
                .is_none()
        );
    }

    #[test]
    fn table_mutate_modifies_value() {
        let store = KvStore::new();
        store.table::<Items>(OWNER).insert("k", "hello".to_owned());
        store
            .table::<Items>(OWNER)
            .with_mut(&"k", |v| v.push('!'))
            .unwrap();
        assert_eq!(
            store.table::<Items>(OWNER).get("k"),
            Some("hello!".to_owned())
        );
    }

    #[test]
    fn table_remove_makes_get_return_none() {
        let store = KvStore::new();
        store.table::<Items>(OWNER).insert("k", "v".to_owned());
        store.table::<Items>(OWNER).remove(&"k");
        assert!(store.table::<Items>(OWNER).get("k").is_none());
    }

    #[test]
    fn table_clear_removes_all_rows() {
        let store = KvStore::new();
        let table = store.table::<Items>(OWNER);
        table.insert("a", "alpha".to_owned());
        table.insert("b", "beta".to_owned());
        table.insert("c", "gamma".to_owned());
        table.clear();
        assert!(table.is_empty());
    }

    #[test]
    fn table_clear_preserves_ownership() {
        let store = KvStore::new();
        store.table::<Items>(OWNER).insert("k", "v".to_owned());
        store.table::<Items>(OWNER).clear();
        // Same owner can still write after clear
        store.table::<Items>(OWNER).insert("k2", "v2".to_owned());
        assert_eq!(store.table::<Items>(OWNER).get("k2"), Some("v2".to_owned()));
    }

    #[test]
    fn table_is_empty_on_fresh_store() {
        let store = KvStore::new();
        assert!(store.table::<Items>(OWNER).is_empty());
    }

    #[test]
    fn table_len_zero_on_fresh_store() {
        let store = KvStore::new();
        assert_eq!(store.table::<Items>(OWNER).len(), 0);
    }

    #[test]
    fn table_len_increases_with_inserts() {
        let store = KvStore::new();
        let table = store.table::<Items>(OWNER);
        table.insert("a", "alpha".to_owned());
        table.insert("b", "beta".to_owned());
        table.insert("c", "gamma".to_owned());
        assert_eq!(table.len(), 3);
    }

    #[test]
    fn table_len_decreases_after_remove() {
        let store = KvStore::new();
        let table = store.table::<Items>(OWNER);
        table.insert("a", "alpha".to_owned());
        table.insert("b", "beta".to_owned());
        table.remove(&"a");
        assert_eq!(table.len(), 1);
    }

    #[test]
    fn table_is_empty_false_after_insert() {
        let store = KvStore::new();
        store.table::<Items>(OWNER).insert("k", "v".to_owned());
        assert!(!store.table::<Items>(OWNER).is_empty());
    }

    #[test]
    fn table_iter_empty_on_fresh_store() {
        let store = KvStore::new();
        let table = store.table::<Items>(OWNER);
        let items: Vec<_> = table.iter().collect();
        assert!(items.is_empty());
    }

    #[test]
    fn table_iter_yields_all_rows() {
        let store = KvStore::new();
        let table = store.table::<Items>(OWNER);
        table.insert("a", "alpha".to_owned());
        table.insert("b", "beta".to_owned());
        let mut items: Vec<_> = table.iter().collect();
        items.sort();
        assert_eq!(
            items,
            vec![(&"a", &"alpha".to_owned()), (&"b", &"beta".to_owned())]
        );
    }

    #[test]
    fn table_iter_reflects_mutations() {
        let store = KvStore::new();
        let table = store.table::<Items>(OWNER);
        table.insert("k", "v1".to_owned());
        table
            .with_mut(&"k", |v| {
                v.clear();
                v.push_str("v2");
            })
            .unwrap();
        let items: Vec<_> = table.iter().collect();
        assert_eq!(items, vec![(&"k", &"v2".to_owned())]);
    }

    #[test]
    fn table_for_each_empty_calls_closure_zero_times() {
        let store = KvStore::new();
        let table = store.table::<Items>(OWNER);
        let mut count = 0;
        table.iter().for_each(|_| count += 1);
        assert_eq!(count, 0);
    }

    #[test]
    fn table_for_each_yields_all_rows() {
        let store = KvStore::new();
        let table = store.table::<Items>(OWNER);
        table.insert("a", "alpha".to_owned());
        table.insert("b", "beta".to_owned());
        let mut items: Vec<_> = Vec::new();
        table.iter().for_each(|(k, v)| items.push((*k, v.clone())));
        items.sort();
        assert_eq!(
            items,
            vec![("a", "alpha".to_owned()), ("b", "beta".to_owned())]
        );
    }

    #[test]
    fn table_with_iter_mut_modifies_values() {
        let store = KvStore::new();
        let table = store.table::<Items>(OWNER);
        table.insert("k", "hello".to_owned());
        table.with_iter_mut(|i| i.next().unwrap().1.push('!'));
        assert_eq!(table.get("k"), Some("hello!".to_owned()));
    }

    #[test]
    fn table_with_iter_mut_empty_yields_none() {
        let store = KvStore::new();
        let table = store.table::<Items>(OWNER);
        let count = table.with_iter_mut(|i| i.count());
        assert_eq!(count, 0);
    }

    #[test]
    fn table_with_iter_mut_visits_all_rows() {
        let store = KvStore::new();
        let table = store.table::<Items>(OWNER);
        table.insert("a", "x".to_owned());
        table.insert("b", "y".to_owned());
        table.insert("c", "z".to_owned());
        table.with_iter_mut(|i| {
            for (_, v) in i {
                v.push('!');
            }
        });
        assert_eq!(table.get("a"), Some("x!".to_owned()));
        assert_eq!(table.get("b"), Some("y!".to_owned()));
        assert_eq!(table.get("c"), Some("z!".to_owned()));
    }

    #[test]
    fn table_iter_keys_cloned_empty() {
        let store = KvStore::new();
        let table = store.table::<Items>(OWNER);
        let keys: Vec<_> = table.keys().collect();
        assert!(keys.is_empty());
    }

    #[test]
    fn table_iter_keys_cloned_yields_all_keys() {
        let store = KvStore::new();
        let table = store.table::<Items>(OWNER);
        table.insert("a", "alpha".to_owned());
        table.insert("b", "beta".to_owned());
        let mut keys: Vec<_> = table.keys().copied().collect();
        keys.sort();
        assert_eq!(keys, vec!["a", "b"]);
    }

    #[test]
    fn table_iter_values_cloned_empty() {
        let store = KvStore::new();
        let table = store.table::<Items>(OWNER);
        let values: Vec<_> = table.values().collect();
        assert!(values.is_empty());
    }

    #[test]
    fn table_iter_values_cloned_yields_all_values() {
        let store = KvStore::new();
        let table = store.table::<Items>(OWNER);
        table.insert("a", "alpha".to_owned());
        table.insert("b", "beta".to_owned());
        let mut values: Vec<_> = table.values().collect();
        values.sort();
        assert_eq!(values, vec!["alpha", "beta"]);
    }

    #[test]
    #[cfg(debug_assertions)]
    #[should_panic(expected = "Ownership violation")]
    fn table_insert_wrong_owner_panics() {
        let store = KvStore::new();
        store.table::<Items>(OTHER).insert("k", "v".to_owned());
    }

    #[test]
    #[cfg_attr(debug_assertions, should_panic(expected = "Ownership violation"))]
    fn table_mutate_wrong_owner_panics() {
        let store = KvStore::new();
        store
            .table::<Items>(OTHER)
            .with_mut(&"k", |v| v.len())
            .unwrap_err();
    }

    #[test]
    #[cfg_attr(debug_assertions, should_panic(expected = "Ownership violation"))]
    fn table_remove_wrong_owner_panics() {
        let store = KvStore::new();
        store.table::<Items>(OTHER).remove(&"k");
    }

    #[test]
    #[cfg_attr(debug_assertions, should_panic(expected = "Ownership violation"))]
    fn table_clear_wrong_owner_panics() {
        let store = KvStore::new();
        store.table::<Items>(OTHER).clear();
    }

    #[test]
    fn table_remove_used_in_statement_position() {
        let store = KvStore::new();
        store.table::<Items>(OWNER).insert("k", "v".to_owned());
        store.table::<Items>(OWNER).remove(&"k");
        assert_eq!(store.table::<Items>(OWNER).get("k"), None);
    }
}
