//! KvStore transactional API.
//!
//! Most of the implementation of transactions is in the [`storage`](crate::storage) module.
//!
//! # Views and aliasing
//!
//! A transaction generated by the schema macros has a field (a 'view') for each table and
//! singleton in the store, e.g., [`TableTransaction`]. Views can be used independently, so the
//! borrow checker allows a user to hold mutable access to two different tables (e.g., an iterator
//! over one table while inserting into another). To make this sound, each view only ever creates
//! references to its own table or singleton, never to the whole store: all views of a transaction
//! share a raw pointer to the storage (see [`Transaction`]) and project it to their own data. The
//! schema macros create exactly one view per table and singleton, so views never alias.
//!
//! Views share ownership of the transaction (via an `Rc`), so a view which is moved out of its
//! transaction (e.g., swapped with the view of another transaction) keeps the store locked and
//! stays valid. Committing a transaction requires that none of its views are held elsewhere.

use std::{
    borrow::Borrow,
    hash::Hash,
    marker::PhantomData,
    num::NonZeroU64,
    ptr::NonNull,
    rc::Rc,
    sync::{RwLockReadGuard, RwLockWriteGuard},
};

use crate::{
    KvStore, Owner, Result,
    iter::{Keys, KeysAndValues, Values},
    operations::{SingletonMut, SingletonRef, TableMut, TableRef},
    schema::{self, TableDesc},
    storage::{Storage, Table, VersionedValue},
};

/// Uniquely identifies a transaction.
///
/// Guaranteed to be non-zero so that `size_of::<Option<TxnId>>() == size_of::<TxnId>()`.
#[derive(Copy, Clone, Debug, PartialEq, Eq, PartialOrd, Ord)]
pub struct TxnId(NonZeroU64);

impl TxnId {
    pub(crate) const FIRST: Self = TxnId(NonZeroU64::new(1).unwrap());

    pub(crate) fn next(self) -> Self {
        TxnId(self.0.checked_add(1).unwrap())
    }

    #[cfg(test)]
    pub(crate) fn new(n: u64) -> Self {
        TxnId(NonZeroU64::new(n).unwrap())
    }
}

/// A transaction object generated by the schema macros.
pub trait SchemaTransaction {
    /// Commit the transaction.
    fn commit(self) -> Result<()>;
    /// Rollback the transaction.
    fn rollback(self);
}

impl<TableStorage: schema::GeneratedStorage> KvStore<TableStorage> {
    /// Start a transaction.
    ///
    /// Blocks until the store's global lock is available for write access.
    pub fn begin_transaction(&self, owner: Owner) -> TableStorage::Transaction<'_> {
        let mut guard = self.get_write_lock();
        let id = guard.begin_transaction();

        TableStorage::make_txn(Transaction::new(guard, owner, id))
    }

    /// Start a transaction.
    ///
    /// Returns `None` if the store's global lock is unavailable for write access.
    pub fn try_begin_transaction(&self, owner: Owner) -> Option<TableStorage::Transaction<'_>> {
        self.clear_lock_poison();

        let mut guard = match self.storage.try_write() {
            Ok(g) => g,
            _ => return None,
        };

        // Garbage-collect any abandoned transaction before starting a new one (matches the blocking
        // `begin_transaction`, which goes through `get_write_lock`).
        guard.clear_transaction();
        let id = guard.begin_transaction();

        Some(TableStorage::make_txn(Transaction::new(guard, owner, id)))
    }

    /// Start a read-only transaction (i.e., only supports non-mutating access to the store, but
    /// all reads are guaranteed to be atomic).
    ///
    /// Blocks until the store's global lock is available for read access.
    pub fn begin_ro_transaction(&self, owner: Owner) -> TableStorage::RoTransaction<'_> {
        let guard = self.get_read_lock();

        TableStorage::make_ro_txn(RoTransaction {
            guard,
            owner,
            _not_send_or_sync: PhantomData,
        })
    }

    /// Start a read-only transaction (i.e., only supports non-mutating access to the store, but
    /// all reads are guaranteed to be atomic).
    ///
    /// Returns `None` if the store's global lock is unavailable for read access.
    pub fn try_begin_ro_transaction(
        &self,
        owner: Owner,
    ) -> Option<TableStorage::RoTransaction<'_>> {
        self.clear_lock_poison();

        if let Ok(guard) = self.storage.try_read() {
            return Some(TableStorage::make_ro_txn(RoTransaction {
                guard,
                owner,
                _not_send_or_sync: PhantomData,
            }));
        }

        // Garbage-collect the abandoned transaction before reading.
        let Ok(mut guard) = self.storage.try_write() else {
            return None;
        };

        guard.clear_transaction();
        let guard = RwLockWriteGuard::downgrade(guard);

        Some(TableStorage::make_ro_txn(RoTransaction {
            guard,
            owner,
            _not_send_or_sync: PhantomData,
        }))
        // We only try once, rather than loop because if the user is calling `try_begin_...`, they
        // presumably don't want to wait and we'd only need to retry if someone else grabbed the
        // the lock before we could.
    }
}

/// Access singleton data in the store as part of a transaction.
///
/// `S` describes the singleton and instances are generated by the schema macros.
pub struct SingletonTransaction<
    'a,
    TableStorage: schema::GeneratedStorage + 'static,
    S: schema::SingletonDesc<Storage = TableStorage>,
> {
    /// Invariant: no other view of `txn` accesses `S` (see `new`).
    txn: Rc<Transaction<'a, TableStorage>>,
    desc: PhantomData<S>,
}

impl<
    'a,
    TableStorage: schema::GeneratedStorage + 'static,
    S: schema::SingletonDesc<Storage = TableStorage>,
> SingletonTransaction<'a, TableStorage, S>
{
    /// Create a view of `S` within `txn`.
    ///
    /// # Safety
    ///
    /// [`SingletonDesc::value_ptr`](schema::SingletonDesc::value_ptr) for `S` must return a pointer
    /// to `S`'s field within the storage it is given.
    ///
    /// While the returned view is alive, no other view of `txn` may access `S`'s data. I.e., the
    /// caller must not create another `SingletonTransaction` for `S` from `txn`, and every other
    /// view created from `txn` must only access data disjoint from `S`'s field in the storage.
    #[doc(hidden)]
    pub unsafe fn new(txn: Rc<Transaction<'a, TableStorage>>) -> Self {
        SingletonTransaction {
            txn,
            desc: PhantomData,
        }
    }

    fn owner(&self) -> Owner {
        self.txn.owner
    }

    fn value_ptr(&self) -> *mut VersionedValue<Option<S::Value>> {
        let storage = self.txn.storage.as_ptr();
        // SAFETY: `storage` is valid while `self.txn` is alive (by the invariant of
        // `Transaction::storage`), which satisfies the precondition of `value_ptr`. Only raw
        // pointers are created, so this does not alias any references held by other views.
        unsafe { S::value_ptr(&raw mut (*storage).tables) }
    }

    fn value_ref(&self) -> SingletonRef<'_, S> {
        // SAFETY: the pointer points to `S`'s field in the storage (by the safety requirements of
        // `new`), which is valid while `self` is borrowed (see `value_ptr`). No other view
        // accesses `S` (by the invariant of `self.txn`), and this view only creates a mutable
        // reference to `S`'s data while `self` is mutably borrowed (in `value_mut`), so there are
        // no mutable references to the data while `self` is borrowed.
        let value = unsafe { &*self.value_ptr() };
        SingletonRef::new(value, self.txn.id)
    }

    fn value_mut(&mut self) -> SingletonMut<'_, S> {
        // SAFETY: as for `value_ref`, and since `self` is mutably borrowed no other references to
        // `S`'s data created by this view can be alive.
        let value = unsafe { &mut *self.value_ptr() };
        SingletonMut::new(value, self.txn.id)
    }

    /// Get a single value from the store by cloning the value.
    ///
    /// Returns `None` if there is no value for the specified key.
    pub fn get(&self) -> Option<S::Value>
    where
        S::Value: Clone,
    {
        self.value_ref().get().cloned()
    }

    /// Get immutable access to a value in the store by reference.
    ///
    /// Returns `None` (and does not call `f`) if there is no value for the specified key.
    pub fn with<T>(&self, f: impl FnOnce(&S::Value) -> T) -> Option<T> {
        self.value_ref().get().map(f)
    }

    /// Get mutable access to a value in the store by reference.
    ///
    /// Returns `None` (and does not call `f`) if there is no value for the specified key.
    pub fn with_mut<T>(&mut self, f: impl FnOnce(&mut S::Value) -> T) -> Option<T>
    where
        S::Value: Clone + PartialEq,
    {
        let owner = self.owner();
        self.value_mut().with_mut(f, owner)
    }

    /// Insert a single value into the store.
    pub fn insert(&mut self, value: S::Value) {
        let owner = self.owner();
        self.value_mut().insert(value, owner)
    }

    /// Remove a single value from the store.
    pub fn remove(&mut self) {
        let owner = self.owner();
        self.value_mut().remove(owner)
    }
}

/// Access singleton data in the store as part of a read-only transaction.
///
/// `S` describes the singleton and instances are generated by the schema macros.
pub struct RoSingletonTransaction<
    'a,
    TableStorage: schema::GeneratedStorage + 'static,
    S: schema::SingletonDesc<Storage = TableStorage>,
> {
    txn: Rc<RoTransaction<'a, TableStorage>>,
    desc: PhantomData<S>,
}

impl<
    'a,
    TableStorage: schema::GeneratedStorage + 'static,
    S: schema::SingletonDesc<Storage = TableStorage>,
> RoSingletonTransaction<'a, TableStorage, S>
{
    /// Create a view of `S` within `txn`.
    #[doc(hidden)]
    pub fn new(txn: Rc<RoTransaction<'a, TableStorage>>) -> Self {
        RoSingletonTransaction {
            txn,
            desc: PhantomData,
        }
    }

    fn value_ref(&self) -> SingletonRef<'_, S> {
        SingletonRef::from_storage(&self.txn.guard)
    }

    /// Get a single value from the store by cloning the value.
    ///
    /// Returns `None` if there is no value for the specified key.
    pub fn get(&self) -> Option<S::Value>
    where
        S::Value: Clone,
    {
        self.value_ref().get().cloned()
    }

    /// Get immutable access to a value in the store by reference.
    ///
    /// Returns `None` (and does not call `f`) if there is no value for the specified key.
    pub fn with<T>(&self, f: impl FnOnce(&S::Value) -> T) -> Option<T> {
        self.value_ref().get().map(f)
    }
}

/// Access tabular data in the store as part of a transaction.
///
/// `D` describes the table and instances are generated by the schema macros.
pub struct TableTransaction<
    'a,
    TableStorage: schema::GeneratedStorage + 'static,
    D: TableDesc<Storage = TableStorage>,
> {
    /// Invariant: no other view of `txn` accesses `D`'s table (see `new`).
    txn: Rc<Transaction<'a, TableStorage>>,
    desc: PhantomData<D>,
}

impl<'a, TableStorage: schema::GeneratedStorage + 'static, D: TableDesc<Storage = TableStorage>>
    TableTransaction<'a, TableStorage, D>
{
    /// Create a view of `D`'s table within `txn`.
    ///
    /// # Safety
    ///
    /// [`TableDesc::table_ptr`] for `D` must return a pointer to `D`'s field within the storage it
    /// is given.
    ///
    /// While the returned view is alive, no other view of `txn` may access `D`'s table (including
    /// its indexes). I.e., the caller must not create another `TableTransaction` for `D` from
    /// `txn`, and every other view created from `txn` must only access data disjoint from `D`'s
    /// field in the storage.
    #[doc(hidden)]
    pub unsafe fn new(txn: Rc<Transaction<'a, TableStorage>>) -> Self {
        TableTransaction {
            txn,
            desc: PhantomData,
        }
    }

    fn owner(&self) -> Owner {
        self.txn.owner
    }

    fn table_ptr(&self) -> *mut Table<D, D::IndexStorage> {
        let storage = self.txn.storage.as_ptr();
        // SAFETY: `storage` is valid while `self.txn` is alive (by the invariant of
        // `Transaction::storage`), which satisfies the precondition of `table_ptr`. Only raw
        // pointers are created, so this does not alias any references held by other views.
        unsafe { D::table_ptr(&raw mut (*storage).tables) }
    }

    /// Read access to the table, for as long as `self` is borrowed.
    pub(crate) fn table_ref(&self) -> TableRef<'_, D> {
        // SAFETY: the pointer points to `D`'s field in the storage (by the safety requirements of
        // `new`), which is valid while `self` is borrowed (see `table_ptr`). No other view
        // accesses `D`'s table (by the invariant of `self.txn`), and this view only creates a
        // mutable reference to the table while `self` is mutably borrowed (in `table_mut`, which
        // is also how `IndexTransaction` mutates the table), so there are no mutable references to
        // the table while `self` is borrowed.
        let table = unsafe { &*self.table_ptr() };
        TableRef::new(table, self.txn.id)
    }

    /// Mutable access to the table, for as long as `self` is borrowed.
    pub(crate) fn table_mut(&mut self) -> TableMut<'_, D> {
        // SAFETY: as for `table_ref`, and since `self` is mutably borrowed no other references to
        // the table created by this view can be alive.
        let table = unsafe { &mut *self.table_ptr() };
        TableMut::new(table, self.txn.id, self.txn.max_committed_id)
    }

    /// The owner of this transaction.
    pub(crate) fn txn_owner(&self) -> Owner {
        self.owner()
    }

    /// The number of key/value pairs in the table.
    pub fn len(&self) -> usize {
        self.table_ref().len()
    }

    /// True if the table is empty.
    pub fn is_empty(&self) -> bool {
        self.table_ref().is_empty()
    }

    /// Clear a table by removing all its KVs.
    pub fn clear(&mut self) {
        let owner = self.owner();
        self.table_mut().clear(owner)
    }

    /// Get a row of the table from the store by cloning the value.
    ///
    /// Returns `None` if there is no value for the specified key.
    pub fn get<Q>(&self, key: &Q) -> Option<D::Value>
    where
        D::Value: Clone,
        D::Key: Borrow<Q>,
        Q: ?Sized + Hash + Eq,
    {
        self.table_ref().get(key).cloned()
    }

    /// Get immutable access to a row of the table in the store by reference.
    ///
    /// Returns `None` (and does not call `f`) if there is no value for the specified key.
    pub fn with<Q, T>(&self, key: &Q, f: impl FnOnce(&D::Value) -> T) -> Option<T>
    where
        D::Key: Borrow<Q>,
        Q: ?Sized + Hash + Eq,
    {
        self.table_ref().get(key).map(f)
    }

    /// Insert a value into the table.
    pub fn insert(&mut self, key: D::Key, value: D::Value) {
        let owner = self.owner();
        self.table_mut().insert(key, value, owner)
    }

    /// Get mutable access to a row of the table in the store in the store.
    ///
    /// Returns `None` (and does not call `f`) if there is no value for the specified key.
    pub fn with_mut<Q, T>(&mut self, key: &Q, f: impl FnOnce(&mut D::Value) -> T) -> Option<T>
    where
        D::Key: Borrow<Q>,
        Q: ?Sized + Hash + Eq + ToOwned<Owned = D::Key>,
        D::Value: Clone + PartialEq,
    {
        let owner = self.owner();
        self.table_mut().with_mut(key, f, owner)
    }

    /// Remove a row from the table.
    pub fn remove<Q>(&mut self, key: &Q)
    where
        D::Key: Borrow<Q>,
        Q: ?Sized + Hash + Eq + ToOwned<Owned = D::Key>,
    {
        let owner = self.owner();
        self.table_mut().remove(key, owner)
    }

    /// Iterate all the key/value pairs in a table.
    pub fn iter(&self) -> impl Iterator<Item = (&D::Key, &D::Value)> {
        self.table_ref().iter::<KeysAndValues>()
    }

    /// Iterate all the keys in a table.
    pub fn keys(&self) -> impl Iterator<Item = &D::Key> {
        self.table_ref().iter::<Keys>()
    }

    /// Iterate all the values in a table.
    pub fn values(&self) -> impl Iterator<Item = &D::Value> {
        self.table_ref().iter::<Values>()
    }

    /// Iterate all the key/value pairs in a table, with mutable access to the values.
    ///
    /// Access is scoped by a closure rather than by returning an iterator, because the table's
    /// indexes are updated from the mutated values once `f` returns.
    pub fn with_iter_mut<F, T>(&mut self, f: F) -> T
    where
        F: for<'b> FnOnce(&mut dyn Iterator<Item = (&'b D::Key, &'b mut D::Value)>) -> T,
        D::Value: Clone + PartialEq,
    {
        let owner = self.owner();
        self.table_mut().with_iter_mut(owner, f)
    }
}

impl<
    'a,
    TableStorage: schema::GeneratedStorage + 'static,
    D: schema::Indexable<Storage = TableStorage>,
> TableTransaction<'a, TableStorage, D>
{
    /// Access the table via its indexes.
    ///
    /// Returns a macro-generated struct with a method for each index declared for the table; each
    /// method returns an [`IndexTransaction`](crate::IndexTransaction) which gives access to the
    /// table using that index's key, as part of this transaction.
    ///
    /// # Example:
    ///
    /// ```rust,ignore
    /// let value = txn.Foo.indexes().bar().get(key).unwrap();
    /// ```
    ///
    /// Here `Foo` is a table and `bar` is an index over `Foo` using the `bar` field as foreign key.
    pub fn indexes(&mut self) -> D::TransactionIndexes<'a, '_> {
        self.into()
    }
}

/// Access tabular data in the store as part of a read-only transaction.
///
/// `D` describes the table and instances are generated by the schema macros.
pub struct RoTableTransaction<
    'a,
    TableStorage: schema::GeneratedStorage + 'static,
    D: schema::TableDesc<Storage = TableStorage>,
> {
    txn: Rc<RoTransaction<'a, TableStorage>>,
    desc: PhantomData<D>,
}

impl<
    'guard,
    TableStorage: schema::GeneratedStorage + 'static,
    D: schema::TableDesc<Storage = TableStorage>,
> RoTableTransaction<'guard, TableStorage, D>
{
    /// Create a view of `D`'s table within `txn`.
    #[doc(hidden)]
    pub fn new(txn: Rc<RoTransaction<'guard, TableStorage>>) -> Self {
        RoTableTransaction {
            txn,
            desc: PhantomData,
        }
    }

    /// Read access to the table, for as long as `self` is borrowed.
    pub(crate) fn table_ref(&self) -> TableRef<'_, D> {
        TableRef::from_storage(&self.txn.guard)
    }

    /// The number of key/value pairs in the table.
    pub fn len(&self) -> usize {
        self.table_ref().len()
    }

    /// True if the table is empty.
    pub fn is_empty(&self) -> bool {
        self.table_ref().is_empty()
    }

    /// Get a row of the table from the store by cloning the value.
    ///
    /// Returns `None` if there is no value for the specified key.
    pub fn get<Q>(&self, key: &Q) -> Option<D::Value>
    where
        D::Value: Clone,
        D::Key: Borrow<Q>,
        Q: ?Sized + Hash + Eq,
    {
        self.table_ref().get(key).cloned()
    }

    /// Get immutable access to a row of the table in the store by reference.
    ///
    /// Returns `None` (and does not call `f`) if there is no value for the specified key.
    pub fn with<Q, T>(&self, key: &Q, f: impl FnOnce(&D::Value) -> T) -> Option<T>
    where
        D::Key: Borrow<Q>,
        Q: ?Sized + Hash + Eq,
    {
        self.table_ref().get(key).map(f)
    }

    /// Iterate all the key/value pairs in a table.
    pub fn iter(&self) -> impl Iterator<Item = (&D::Key, &D::Value)> {
        self.table_ref().iter::<KeysAndValues>()
    }

    /// Iterate all the keys in a table.
    pub fn keys(&self) -> impl Iterator<Item = &D::Key> {
        self.table_ref().iter::<Keys>()
    }

    /// Iterate all the values in a table.
    pub fn values(&self) -> impl Iterator<Item = &D::Value> {
        self.table_ref().iter::<Values>()
    }
}

impl<
    'guard,
    TableStorage: schema::GeneratedStorage + 'static,
    D: schema::Indexable<Storage = TableStorage>,
> RoTableTransaction<'guard, TableStorage, D>
{
    /// Access the table via its indexes.
    ///
    /// Returns a macro-generated struct with a field for each index declared for the table; each
    /// field is a [`RoIndexTransaction`](crate::RoIndexTransaction) which gives read-only access to
    /// the table using that index's key, as part of this transaction.
    ///
    /// # Example:
    ///
    /// ```rust,ignore
    /// let value = txn.Foo.indexes().bar.get(key).unwrap();
    /// ```
    ///
    /// Here `Foo` is a table and `bar` is an index over `Foo` using the `bar` field as foreign key.
    pub fn indexes(&self) -> D::RoTransactionIndexes<'guard, '_> {
        self.into()
    }
}

/// A read/write transaction over a [`KvStore`].
///
/// Create a transaction by calling [`KvStore::begin_transaction`] or [`KvStore::try_begin_transaction`].
/// A transaction holds a write lock on the whole store while it is active so ensure that code within
/// a transaction is relatively quick to execute and that you drop transactions as soon as possible
/// ([`Transaction::commit`] can be used for this).
///
/// A transaction must not be kept alive over an `await` point. This can lead to deadlock.
pub struct Transaction<'guard, TableStorage: schema::GeneratedStorage> {
    /// Holds the store's write lock for the duration of the transaction.
    ///
    /// Invariant: `guard.is_some()` except between commit and drop.
    ///
    /// The guard is only dereferenced when there are no views of the transaction (at commit and
    /// rollback). Views access the storage via `storage` instead, since dereferencing the guard
    /// would create a reference to the whole storage and thus alias references to tables held by
    /// other views.
    guard: Option<RwLockWriteGuard<'guard, Storage<TableStorage>>>,
    /// The locked storage.
    ///
    /// Invariant: valid for reads and writes while `self` is alive and `guard.is_some()` (derived
    /// from `guard` when the transaction is created, and the storage is exclusively locked by
    /// `guard`).
    storage: NonNull<Storage<TableStorage>>,
    pub(crate) owner: Owner,
    id: TxnId,
    /// The id of the most recently committed transaction when this transaction began (this cannot
    /// change until this transaction is committed).
    max_committed_id: TxnId,
    // Enforce the transaction is not `Send` or `Sync` so that it isn't accidentally held over an
    // await point (at least with a parallel async runtime), etc.
    _not_send_or_sync: PhantomData<*const ()>,
}

impl<'guard, TableStorage: schema::GeneratedStorage> Drop for Transaction<'guard, TableStorage> {
    fn drop(&mut self) {
        if let Some(guard) = &mut self.guard {
            guard.rollback_transaction(self.id);
        }
    }
}

impl<'guard, TableStorage: schema::GeneratedStorage> Transaction<'guard, TableStorage> {
    fn new(
        mut guard: RwLockWriteGuard<'guard, Storage<TableStorage>>,
        owner: Owner,
        id: TxnId,
    ) -> Self {
        let max_committed_id = guard.max_committed_id();
        let storage = NonNull::from(&mut *guard);
        Transaction {
            guard: Some(guard),
            storage,
            owner,
            id,
            max_committed_id,
            _not_send_or_sync: PhantomData,
        }
    }

    /// Commit this transaction.
    pub fn commit(mut self) -> Result<()> {
        let id = self.id;
        let notifications = self.guard.as_mut().unwrap().commit_transaction(id)?;
        let guard = self.guard.take().unwrap();
        let guard = RwLockWriteGuard::downgrade(guard);
        guard.subscriptions.notify(notifications);

        Ok(())
    }

    /// Commit a transaction shared with its views (used by the schema macros).
    ///
    /// Panics if `txn` is not the only reference to the transaction, i.e., if any of its views are
    /// still alive (e.g., because they have been moved into another transaction).
    #[doc(hidden)]
    pub fn commit_shared(txn: Rc<Self>) -> Result<()> {
        Rc::into_inner(txn)
            .expect("a transaction cannot be committed while any of its fields are held elsewhere")
            .commit()
    }

    /// Explicitly rollback this transaction.
    ///
    /// A transaction can also be rolled-back by dropping it without first calling `commit`.
    pub fn rollback(self) {
        // Dropping `self` causes the rollback.
    }
}

/// A read-only transaction over a [`KvStore`].
///
/// Create a read-only transaction by calling [`KvStore::begin_ro_transaction`] or [`KvStore::try_begin_ro_transaction`].
/// A read-only transaction holds a read lock on the whole store while it is active so ensure that
/// code within a transaction is relatively quick to execute and that you drop transactions as soon
/// as possible([`RoTransaction::commit`] can be used for this).
///
/// A transaction must not be kept alive over an `await` point. This can lead to deadlock.
pub struct RoTransaction<'guard, TableStorage: schema::GeneratedStorage> {
    pub(crate) guard: RwLockReadGuard<'guard, Storage<TableStorage>>,
    // Currently unused, since reads are not protected by ownership.
    #[allow(dead_code)]
    owner: Owner,
    // Enforce the transaction is not `Send` or `Sync` so that it isn't accidentally held over an
    // await point (at least with a parallel async runtime), etc.
    _not_send_or_sync: PhantomData<*const ()>,
}

impl<'guard, TableStorage: schema::GeneratedStorage> RoTransaction<'guard, TableStorage> {
    /// Commit this transaction.
    ///
    /// This simply moves and drops the `RoTransaction` object. It is optional to call and currently
    /// always succeeds. You can use this method to release the transaction's lock on the store
    /// without needing an explicit scope.
    pub fn commit(self) -> Result<()> {
        // drop `self` to release the lock.
        Ok(())
    }

    /// Explicitly rollback this transaction.
    ///
    /// Like `commit`, this only drops this transaction's lock.
    pub fn rollback(self) {
        // drop `self` to release the lock.
    }
}

#[cfg(test)]
mod test {
    use std::sync::Arc;

    use crate::store;

    store!(
        kvs: { Count(u64; OWNER), Shared(Arc<String>; OWNER) }
        tables: { Items(&'static str => String; OWNER), Counters(u32 => u64; OWNER) }
    );

    const OWNER: &str = "owner";
    #[cfg(debug_assertions)]
    const OTHER: &str = "other";

    #[test]
    fn try_begin_transaction_returns_some_when_unlocked() {
        let store = KvStore::new();
        assert!(store.try_begin_transaction(OWNER).is_some());
    }

    #[test]
    fn begin_ro_transaction_works() {
        let store = KvStore::new();
        store.Count.insert(OWNER, 7);
        let txn = store.begin_ro_transaction(OWNER);
        assert_eq!(txn.Count.get(), Some(7));
    }

    #[test]
    fn try_begin_ro_transaction_returns_some_when_unlocked() {
        let store = KvStore::new();
        assert!(store.try_begin_ro_transaction(OWNER).is_some());
    }

    #[test]
    fn try_begin_transaction_after_commit_sees_committed() {
        let store = KvStore::new();
        let mut txn = store.begin_transaction(OWNER);
        txn.Count.insert(7);
        txn.commit().unwrap();

        let txn = store.try_begin_transaction(OWNER).unwrap();
        assert_eq!(txn.Count.get(), Some(7));
    }

    #[test]
    fn try_begin_transaction_after_rollback_sees_pre_txn() {
        let store = KvStore::new();
        store.Count.insert(OWNER, 1);
        {
            let mut txn = store.begin_transaction(OWNER);
            txn.Count.insert(2);
            // dropped without commit -> rolled back
        }
        let txn = store.try_begin_transaction(OWNER).unwrap();
        assert_eq!(txn.Count.get(), Some(1));
    }

    #[test]
    fn try_begin_ro_transaction_after_commit_sees_committed() {
        let store = KvStore::new();
        let mut txn = store.begin_transaction(OWNER);
        txn.Count.insert(7);
        txn.commit().unwrap();

        let txn = store.try_begin_ro_transaction(OWNER).unwrap();
        assert_eq!(txn.Count.get(), Some(7));
    }

    #[test]
    fn try_begin_ro_transaction_after_rollback_sees_pre_txn() {
        let store = KvStore::new();
        store.Count.insert(OWNER, 1);
        {
            let mut txn = store.begin_transaction(OWNER);
            txn.Count.insert(2);
        }
        let txn = store.try_begin_ro_transaction(OWNER).unwrap();
        assert_eq!(txn.Count.get(), Some(1));
    }

    #[test]
    fn txn_get_returns_none_when_absent() {
        let store = KvStore::new();
        let txn = store.begin_transaction(OWNER);
        assert!(txn.Count.get().is_none());
    }

    #[test]
    fn txn_get_returns_value_inserted_in_same_txn() {
        let store = KvStore::new();
        let mut txn = store.begin_transaction(OWNER);
        txn.Count.insert(42);
        assert_eq!(txn.Count.get(), Some(42));
    }

    #[test]
    fn txn_get_returns_value_inserted_before_txn() {
        let store = KvStore::new();
        store.Count.insert(OWNER, 5);
        let txn = store.begin_transaction(OWNER);
        assert_eq!(txn.Count.get(), Some(5));
    }

    #[test]
    fn txn_with_returns_none_and_does_not_call_f_when_absent() {
        let store = KvStore::new();
        let txn = store.begin_transaction(OWNER);
        let mut called = false;
        let result = txn.Count.with(|_| {
            called = true;
        });
        assert!(result.is_none());
        assert!(!called);
    }

    #[test]
    fn txn_with_returns_result_of_f() {
        let store = KvStore::new();
        let mut txn = store.begin_transaction(OWNER);
        txn.Count.insert(5);
        assert_eq!(txn.Count.with(|v| v * 2), Some(10));
    }

    #[test]
    fn txn_remove_makes_get_return_none() {
        let store = KvStore::new();
        let mut txn = store.begin_transaction(OWNER);
        txn.Count.insert(1);
        txn.Count.remove();
        assert!(txn.Count.get().is_none());
    }

    #[test]
    fn txn_with_mut_returns_none_and_does_not_call_f_when_absent() {
        let store = KvStore::new();
        let mut txn = store.begin_transaction(OWNER);
        let mut called = false;
        let result = txn.Count.with_mut(|_| called = true);
        assert!(result.is_none());
        assert!(!called);
    }

    #[test]
    fn txn_with_mut_does_not_insert_when_absent() {
        let store = KvStore::new();
        let mut txn = store.begin_transaction(OWNER);
        txn.Count.with_mut(|v| *v = 7);
        assert!(txn.Count.get().is_none());
    }

    #[test]
    fn txn_with_mut_mutates_value_inserted_before_txn() {
        let store = KvStore::new();
        store.Count.insert(OWNER, 5);
        let mut txn = store.begin_transaction(OWNER);
        txn.Count.with_mut(|v| *v *= 2);
        assert_eq!(txn.Count.get(), Some(10));
    }

    #[test]
    fn txn_with_mut_mutates_value_inserted_in_same_txn() {
        let store = KvStore::new();
        let mut txn = store.begin_transaction(OWNER);
        txn.Count.insert(5);
        txn.Count.with_mut(|v| *v *= 2);
        assert_eq!(txn.Count.get(), Some(10));
    }

    #[test]
    fn txn_with_mut_sees_previous_with_mut_in_same_txn() {
        let store = KvStore::new();
        store.Count.insert(OWNER, 0);
        let mut txn = store.begin_transaction(OWNER);
        txn.Count.with_mut(|v| *v += 1);
        txn.Count.with_mut(|v| *v += 1);
        txn.Count.with_mut(|v| *v += 1);
        assert_eq!(txn.Count.get(), Some(3));
    }

    #[test]
    fn txn_with_mut_returns_none_after_remove_in_same_txn() {
        let store = KvStore::new();
        store.Count.insert(OWNER, 5);
        let mut txn = store.begin_transaction(OWNER);
        txn.Count.remove();
        let mut called = false;
        let result = txn.Count.with_mut(|_| called = true);
        assert!(result.is_none());
        assert!(!called);
        assert!(txn.Count.get().is_none());
    }

    #[test]
    fn txn_writes_visible_after_drop() {
        let store = KvStore::new();
        let mut txn = store.begin_transaction(OWNER);
        txn.Count.insert(42);
        txn.commit().unwrap();

        assert_eq!(store.Count.get(OWNER), Some(42));
    }

    #[test]
    fn txn_table_writes_visible_after_drop() {
        let store = KvStore::new();
        let mut txn = store.begin_transaction(OWNER);
        txn.Items.insert("k", "v".to_owned());
        txn.commit().unwrap();

        assert_eq!(store.Items.get(OWNER, "k"), Some("v".to_owned()));
    }

    #[test]
    #[cfg(debug_assertions)]
    #[should_panic(expected = "Ownership violation")]
    fn txn_insert_wrong_owner_panics() {
        let store = KvStore::new();
        store.Count.insert(OWNER, 1);
        let mut txn = store.begin_transaction(OTHER);
        txn.Count.insert(5);
    }

    #[test]
    #[cfg(debug_assertions)]
    #[should_panic(expected = "Ownership violation")]
    fn txn_with_mut_wrong_owner_panics() {
        let store = KvStore::new();
        store.Count.insert(OWNER, 1);
        let mut txn = store.begin_transaction(OTHER);
        txn.Count.with_mut(|v| *v = 5);
    }

    #[test]
    #[cfg(debug_assertions)]
    #[should_panic(expected = "Ownership violation")]
    fn txn_remove_wrong_owner_panics() {
        let store = KvStore::new();
        store.Count.insert(OWNER, 1);
        let mut txn = store.begin_transaction(OTHER);
        txn.Count.remove();
    }

    #[test]
    fn txn_table_get_returns_none_when_absent() {
        let store = KvStore::new();
        let txn = store.begin_transaction(OWNER);
        let table = &txn.Items;
        assert!(table.get("missing").is_none());
    }

    #[test]
    fn txn_table_get_returns_value_after_insert() {
        let store = KvStore::new();
        let mut txn = store.begin_transaction(OWNER);
        let table = &mut txn.Items;
        table.insert("k", "val".to_owned());
        assert_eq!(table.get("k"), Some("val".to_owned()));
    }

    #[test]
    fn txn_table_with_returns_none_and_does_not_call_f_when_absent() {
        let store = KvStore::new();
        let txn = store.begin_transaction(OWNER);
        let table = &txn.Items;
        let mut called = false;
        let result = table.with("missing", |_| {
            called = true;
        });
        assert!(result.is_none());
        assert!(!called);
    }

    #[test]
    fn txn_table_with_returns_some_after_insert() {
        let store = KvStore::new();
        let mut txn = store.begin_transaction(OWNER);
        let table = &mut txn.Items;
        table.insert("k", "val".to_owned());
        assert_eq!(table.with("k", |s| s.len()), Some(3));
    }

    #[test]
    fn txn_table_mutate_returns_none_when_absent() {
        let store = KvStore::new();
        let mut txn = store.begin_transaction(OWNER);
        let table = &mut txn.Items;
        assert!(table.with_mut(&"missing", |v| v.len()).is_none());
    }

    #[test]
    fn txn_table_mutate_modifies_value() {
        let store = KvStore::new();
        let mut txn = store.begin_transaction(OWNER);
        let table = &mut txn.Items;
        table.insert("k", "hello".to_owned());
        table.with_mut(&"k", |v| v.push('!'));
        assert_eq!(table.get("k"), Some("hello!".to_owned()));
    }

    #[test]
    fn txn_table_remove_makes_get_return_none() {
        let store = KvStore::new();
        let mut txn = store.begin_transaction(OWNER);
        let table = &mut txn.Items;
        table.insert("k", "v".to_owned());
        table.remove(&"k");
        assert!(table.get("k").is_none());
    }

    #[test]
    fn txn_table_clear_removes_all_rows() {
        let store = KvStore::new();
        let mut txn = store.begin_transaction(OWNER);
        let table = &mut txn.Items;
        table.insert("a", "alpha".to_owned());
        table.insert("b", "beta".to_owned());
        table.insert("c", "gamma".to_owned());
        table.clear();
        assert!(table.is_empty());
    }

    #[test]
    fn txn_table_is_empty_on_fresh_store() {
        let store = KvStore::new();
        let txn = store.begin_transaction(OWNER);
        let table = &txn.Items;
        assert!(table.is_empty());
    }

    #[test]
    fn txn_table_len_reflects_inserts() {
        let store = KvStore::new();
        let mut txn = store.begin_transaction(OWNER);
        let table = &mut txn.Items;
        table.insert("a", "alpha".to_owned());
        table.insert("b", "beta".to_owned());
        assert_eq!(table.len(), 2);
    }

    #[test]
    fn txn_table_iter_empty() {
        let store = KvStore::new();
        let txn = store.begin_transaction(OWNER);
        let table = &txn.Items;
        assert_eq!(table.iter().count(), 0);
    }

    #[test]
    fn txn_table_iter_yields_inserted_rows() {
        let store = KvStore::new();
        let mut txn = store.begin_transaction(OWNER);
        let table = &mut txn.Items;
        table.insert("a", "alpha".to_owned());
        table.insert("b", "beta".to_owned());
        let mut items: Vec<_> = table.iter().collect();
        items.sort();
        assert_eq!(
            items,
            vec![(&"a", &"alpha".to_owned()), (&"b", &"beta".to_owned())]
        );
    }

    #[test]
    fn txn_table_for_each_empty_calls_closure_zero_times() {
        let store = KvStore::new();
        let txn = store.begin_transaction(OWNER);
        let table = &txn.Items;
        let mut count = 0;
        table.iter().for_each(|_| count += 1);
        assert_eq!(count, 0);
    }

    #[test]
    fn txn_table_for_each_yields_all_rows() {
        let store = KvStore::new();
        let mut txn = store.begin_transaction(OWNER);
        let table = &mut txn.Items;
        table.insert("a", "alpha".to_owned());
        table.insert("b", "beta".to_owned());
        let mut items: Vec<_> = Vec::new();
        table.iter().for_each(|(k, v)| items.push((*k, v.clone())));
        items.sort();
        assert_eq!(
            items,
            vec![("a", "alpha".to_owned()), ("b", "beta".to_owned())]
        );
    }

    #[test]
    fn txn_table_iter_mut_modifies_values() {
        let store = KvStore::new();
        let mut txn = store.begin_transaction(OWNER);
        let table = &mut txn.Items;
        table.insert("k", "hello".to_owned());
        table.iter_mut().next().unwrap().1.push('!');
        assert_eq!(table.get("k"), Some("hello!".to_owned()));
    }

    #[test]
    fn txn_table_iter_mut_empty_yields_none() {
        let store = KvStore::new();
        let mut txn = store.begin_transaction(OWNER);
        let table = &mut txn.Items;
        assert!(table.iter_mut().next().is_none());
        assert_eq!(table.iter_mut().count(), 0);
    }

    #[test]
    fn txn_table_iter_mut_visits_all_rows() {
        let store = KvStore::new();
        let mut txn = store.begin_transaction(OWNER);
        let table = &mut txn.Items;
        table.insert("a", "x".to_owned());
        table.insert("b", "y".to_owned());
        table.insert("c", "z".to_owned());
        for (_, v) in table.iter_mut() {
            v.push('!');
        }
        assert_eq!(table.get("a"), Some("x!".to_owned()));
        assert_eq!(table.get("b"), Some("y!".to_owned()));
        assert_eq!(table.get("c"), Some("z!".to_owned()));
    }

    // `iter_mut` must respect a `DeleteMask::Some` produced by removing a key earlier in the
    // same transaction: the removed key should not be visited.
    #[test]
    fn txn_table_iter_mut_skips_removed_key() {
        let store = KvStore::new();
        let mut txn = store.begin_transaction(OWNER);
        let table = &mut txn.Items;
        table.insert("a", "x".to_owned());
        table.insert("b", "y".to_owned());
        table.insert("c", "z".to_owned());
        table.remove(&"b");

        let mut keys: Vec<_> = table.iter_mut().map(|(k, _)| *k).collect();
        keys.sort();
        assert_eq!(keys, vec!["a", "c"]);

        // Mutations through the iterator still land, and the removed key stays gone.
        for (_, v) in table.iter_mut() {
            v.push('!');
        }
        assert_eq!(table.get("a"), Some("x!".to_owned()));
        assert!(table.get("b").is_none());
        assert_eq!(table.get("c"), Some("z!".to_owned()));
    }

    // `iter_mut` must respect a `DeleteMask::All` produced by clearing the table earlier in the
    // same transaction: only rows inserted after the clear should be visited.
    #[test]
    fn txn_table_iter_mut_after_clear_visits_only_new_rows() {
        let store = KvStore::new();
        store.Items.insert(OWNER, "a", "x".to_owned());
        store.Items.insert(OWNER, "b", "y".to_owned());

        let mut txn = store.begin_transaction(OWNER);
        let table = &mut txn.Items;
        table.clear();
        table.insert("c", "z".to_owned());

        let mut visited: Vec<_> = table.iter_mut().map(|(k, _)| *k).collect();
        visited.sort();
        assert_eq!(visited, vec!["c"]);

        table.iter_mut().next().unwrap().1.push('!');
        assert_eq!(table.get("c"), Some("z!".to_owned()));
    }

    // Rolling back a transaction that mutated values via `iter_mut` must leave the committed
    // state untouched. This exercises the "all keys modified" (`keys == None`) GC path.
    #[test]
    fn txn_iter_mut_rollback_discards_changes() {
        let store = KvStore::new();
        store.Items.insert(OWNER, "a", "x".to_owned());
        store.Items.insert(OWNER, "b", "y".to_owned());

        let mut txn = store.begin_transaction(OWNER);
        for (_, v) in txn.Items.iter_mut() {
            v.push('!');
        }
        txn.rollback();

        assert_eq!(store.Items.get(OWNER, "a"), Some("x".to_owned()));
        assert_eq!(store.Items.get(OWNER, "b"), Some("y".to_owned()));

        // The store is still usable and a fresh transaction sees the original values.
        let mut txn = store.begin_transaction(OWNER);
        let mut visited: Vec<_> = txn.Items.iter_mut().map(|(k, v)| (*k, v.clone())).collect();
        visited.sort();
        assert_eq!(visited, vec![("a", "x".to_owned()), ("b", "y".to_owned())]);
    }

    #[test]
    fn txn_no_op_with_mut_commit_leaves_value_unchanged() {
        let store = KvStore::new();
        store.Items.insert(OWNER, "k", "a".to_owned());

        let mut txn = store.begin_transaction(OWNER);
        assert_eq!(txn.Items.with_mut(&"k", |v| v.len()), Some(1));
        txn.commit().unwrap();

        assert_eq!(store.Items.get(OWNER, "k"), Some("a".to_owned()));
    }

    #[test]
    fn txn_no_op_with_mut_then_rollback_preserves_value() {
        let store = KvStore::new();
        store.Items.insert(OWNER, "k", "a".to_owned());

        // Take a mutable reference to the row but change nothing, then roll back.
        {
            let mut txn = store.begin_transaction(OWNER);
            txn.Items.with_mut(&"k", |_| {});
        }
        assert_eq!(store.Items.get(OWNER, "k"), Some("a".to_owned()));

        // A second rolled-back transaction, this one writing to the same row.
        {
            let mut txn = store.begin_transaction(OWNER);
            txn.Items.insert("k", "b".to_owned());
        }

        // Neither transaction committed, so the row must still hold its committed value.
        assert_eq!(store.Items.get(OWNER, "k"), Some("a".to_owned()));
    }

    #[test]
    fn txn_no_op_iter_mut_then_rollback_preserves_value() {
        let store = KvStore::new();
        store.Items.insert(OWNER, "k", "a".to_owned());

        {
            let mut txn = store.begin_transaction(OWNER);
            assert_eq!(txn.Items.iter_mut().count(), 1);
        }
        assert_eq!(store.Items.get(OWNER, "k"), Some("a".to_owned()));

        {
            let mut txn = store.begin_transaction(OWNER);
            txn.Items.insert("k", "b".to_owned());
        }

        assert_eq!(store.Items.get(OWNER, "k"), Some("a".to_owned()));
    }

    #[test]
    fn txn_table_iter_keys_cloned_empty() {
        let store = KvStore::new();
        let txn = store.begin_transaction(OWNER);
        let table = &txn.Items;
        let keys: Vec<_> = table.keys().collect();
        assert!(keys.is_empty());
    }

    #[test]
    fn txn_table_iter_keys_cloned_yields_all_keys() {
        let store = KvStore::new();
        let mut txn = store.begin_transaction(OWNER);
        let table = &mut txn.Items;
        table.insert("a", "alpha".to_owned());
        table.insert("b", "beta".to_owned());
        let mut keys: Vec<_> = table.keys().copied().collect();
        keys.sort();
        assert_eq!(keys, vec!["a", "b"]);
    }

    #[test]
    fn txn_table_iter_values_cloned_empty() {
        let store = KvStore::new();
        let txn = store.begin_transaction(OWNER);
        let table = &txn.Items;
        let values: Vec<_> = table.values().collect();
        assert!(values.is_empty());
    }

    #[test]
    fn txn_table_iter_values_cloned_yields_all_values() {
        let store = KvStore::new();
        let mut txn = store.begin_transaction(OWNER);
        let table = &mut txn.Items;
        table.insert("a", "alpha".to_owned());
        table.insert("b", "beta".to_owned());
        let mut values: Vec<_> = table.values().collect();
        values.sort();
        assert_eq!(values, vec!["alpha", "beta"]);
    }

    #[test]
    #[cfg(debug_assertions)]
    #[should_panic(expected = "Ownership violation")]
    fn txn_table_insert_wrong_owner_panics() {
        let store = KvStore::new();
        let mut txn = store.begin_transaction(OTHER);
        txn.Items.insert("k", "v".to_owned());
    }

    #[test]
    #[cfg(debug_assertions)]
    #[should_panic(expected = "Ownership violation")]
    fn txn_table_mutate_wrong_owner_panics() {
        let store = KvStore::new();
        let mut txn = store.begin_transaction(OTHER);
        txn.Items.with_mut(&"k", |v: &mut String| v.len());
    }

    #[test]
    #[cfg(debug_assertions)]
    #[should_panic(expected = "Ownership violation")]
    fn txn_table_remove_wrong_owner_panics() {
        let store = KvStore::new();
        let mut txn = store.begin_transaction(OTHER);
        txn.Items.remove(&"k");
    }

    #[test]
    fn ro_txn_get_returns_none_when_absent() {
        let store = KvStore::new();
        let txn = store.begin_ro_transaction(OWNER);
        assert!(txn.Count.get().is_none());
    }

    #[test]
    fn ro_txn_get_returns_value_inserted_before_txn() {
        let store = KvStore::new();
        store.Count.insert(OWNER, 42);
        let txn = store.begin_ro_transaction(OWNER);
        assert_eq!(txn.Count.get(), Some(42));
    }

    #[test]
    fn ro_txn_with_returns_none_and_does_not_call_f_when_absent() {
        let store = KvStore::new();
        let txn = store.begin_ro_transaction(OWNER);
        let mut called = false;
        let result = txn.Count.with(|_| {
            called = true;
        });
        assert!(result.is_none());
        assert!(!called);
    }

    #[test]
    fn ro_txn_with_returns_some_after_insert() {
        let store = KvStore::new();
        store.Count.insert(OWNER, 4);
        let txn = store.begin_ro_transaction(OWNER);
        assert_eq!(txn.Count.with(|v| v * 2), Some(8));
    }

    #[test]
    fn ro_txn_table_get_returns_none_when_absent() {
        let store = KvStore::new();
        let txn = store.begin_ro_transaction(OWNER);
        let table = &txn.Items;
        assert!(table.get("missing").is_none());
    }

    #[test]
    fn ro_txn_table_get_returns_value_inserted_before_txn() {
        let store = KvStore::new();
        store.Items.insert(OWNER, "k", "val".to_owned());
        let txn = store.begin_ro_transaction(OWNER);
        let table = &txn.Items;
        assert_eq!(table.get("k"), Some("val".to_owned()));
    }

    #[test]
    fn ro_txn_table_with_returns_none_and_does_not_call_f_when_absent() {
        let store = KvStore::new();
        let txn = store.begin_ro_transaction(OWNER);
        let table = &txn.Items;
        let mut called = false;
        let result = table.with("missing", |_| {
            called = true;
        });
        assert!(result.is_none());
        assert!(!called);
    }

    #[test]
    fn ro_txn_table_with_returns_some() {
        let store = KvStore::new();
        store.Items.insert(OWNER, "k", "val".to_owned());
        let txn = store.begin_ro_transaction(OWNER);
        let table = &txn.Items;
        assert_eq!(table.with("k", |s| s.len()), Some(3));
    }

    #[test]
    fn ro_txn_table_len_zero_when_empty() {
        let store = KvStore::new();
        let txn = store.begin_ro_transaction(OWNER);
        let table = &txn.Items;
        assert_eq!(table.len(), 0);
    }

    #[test]
    fn ro_txn_table_len_reflects_pre_txn_inserts() {
        let store = KvStore::new();
        store.Items.insert(OWNER, "a", "alpha".to_owned());
        store.Items.insert(OWNER, "b", "beta".to_owned());
        let txn = store.begin_ro_transaction(OWNER);
        let table = &txn.Items;
        assert_eq!(table.len(), 2);
    }

    #[test]
    fn ro_txn_table_is_empty_true_when_no_rows() {
        let store = KvStore::new();
        let txn = store.begin_ro_transaction(OWNER);
        let table = &txn.Items;
        assert!(table.is_empty());
    }

    #[test]
    fn ro_txn_table_is_empty_false_after_inserts() {
        let store = KvStore::new();
        store.Items.insert(OWNER, "k", "v".to_owned());
        let txn = store.begin_ro_transaction(OWNER);
        let table = &txn.Items;
        assert!(!table.is_empty());
    }

    #[test]
    fn ro_txn_table_iter_empty() {
        let store = KvStore::new();
        let txn = store.begin_ro_transaction(OWNER);
        let table = &txn.Items;
        assert_eq!(table.iter().count(), 0);
    }

    #[test]
    fn ro_txn_table_iter_yields_pre_txn_rows() {
        let store = KvStore::new();
        store.Items.insert(OWNER, "a", "alpha".to_owned());
        store.Items.insert(OWNER, "b", "beta".to_owned());
        let txn = store.begin_ro_transaction(OWNER);
        let table = &txn.Items;
        let mut items: Vec<_> = table.iter().collect();
        items.sort();
        assert_eq!(
            items,
            vec![(&"a", &"alpha".to_owned()), (&"b", &"beta".to_owned())]
        );
    }

    #[test]
    fn ro_txn_table_for_each_empty_calls_closure_zero_times() {
        let store = KvStore::new();
        let txn = store.begin_ro_transaction(OWNER);
        let table = &txn.Items;
        let mut count = 0;
        table.iter().for_each(|_| count += 1);
        assert_eq!(count, 0);
    }

    #[test]
    fn ro_txn_table_for_each_yields_pre_txn_rows() {
        let store = KvStore::new();
        store.Items.insert(OWNER, "a", "alpha".to_owned());
        store.Items.insert(OWNER, "b", "beta".to_owned());
        let txn = store.begin_ro_transaction(OWNER);
        let table = &txn.Items;
        let mut items: Vec<_> = Vec::new();
        table.iter().for_each(|(k, v)| items.push((*k, v.clone())));
        items.sort();
        assert_eq!(
            items,
            vec![("a", "alpha".to_owned()), ("b", "beta".to_owned())]
        );
    }

    #[test]
    fn ro_txn_table_iter_keys_cloned_empty() {
        let store = KvStore::new();
        let txn = store.begin_ro_transaction(OWNER);
        let table = &txn.Items;
        let keys: Vec<_> = table.keys().collect();
        assert!(keys.is_empty());
    }

    #[test]
    fn ro_txn_table_iter_keys_cloned_yields_pre_txn_keys() {
        let store = KvStore::new();
        store.Items.insert(OWNER, "a", "alpha".to_owned());
        store.Items.insert(OWNER, "b", "beta".to_owned());
        let txn = store.begin_ro_transaction(OWNER);
        let table = &txn.Items;
        let mut keys: Vec<_> = table.keys().copied().collect();
        keys.sort();
        assert_eq!(keys, vec!["a", "b"]);
    }

    #[test]
    fn ro_txn_table_iter_values_cloned_empty() {
        let store = KvStore::new();
        let txn = store.begin_ro_transaction(OWNER);
        let table = &txn.Items;
        let values: Vec<_> = table.values().collect();
        assert!(values.is_empty());
    }

    #[test]
    fn ro_txn_table_iter_values_cloned_yields_pre_txn_values() {
        let store = KvStore::new();
        store.Items.insert(OWNER, "a", "alpha".to_owned());
        store.Items.insert(OWNER, "b", "beta".to_owned());
        let txn = store.begin_ro_transaction(OWNER);
        let table = &txn.Items;
        let mut values: Vec<_> = table.values().collect();
        values.sort();
        assert_eq!(values, vec!["alpha", "beta"]);
    }

    #[test]
    fn commit_returns_ok() {
        let store = KvStore::new();
        let mut txn = store.begin_transaction(OWNER);
        txn.Count.insert(1);
        assert!(txn.commit().is_ok());
    }

    #[test]
    fn txn_table_remove_then_commit_row_absent() {
        let store = KvStore::new();
        store.Items.insert(OWNER, "k", "v".to_owned());

        let mut txn = store.begin_transaction(OWNER);
        txn.Items.remove(&"k");
        txn.commit().unwrap();

        assert_eq!(store.Items.get(OWNER, "k"), None);
    }

    #[test]
    fn txn_table_clear_then_commit_empty() {
        let store = KvStore::new();
        store.Items.insert(OWNER, "a", "1".to_owned());
        store.Items.insert(OWNER, "b", "2".to_owned());

        let mut txn = store.begin_transaction(OWNER);
        txn.Items.clear();
        txn.commit().unwrap();

        assert!(store.Items.is_empty());
    }

    #[test]
    fn txn_singleton_remove_then_commit_absent() {
        let store = KvStore::new();
        store.Count.insert(OWNER, 7);

        let mut txn = store.begin_transaction(OWNER);
        txn.Count.remove();
        txn.commit().unwrap();

        assert_eq!(store.Count.get(OWNER), None);
    }

    #[test]
    fn txn_singleton_with_mut_then_commit_visible() {
        let store = KvStore::new();
        store.Count.insert(OWNER, 7);

        let mut txn = store.begin_transaction(OWNER);
        txn.Count.with_mut(|v| *v += 1);
        txn.commit().unwrap();

        assert_eq!(store.Count.get(OWNER), Some(8));
    }

    #[test]
    fn txn_singleton_with_mut_commits_atomically_with_other_writes() {
        let store = KvStore::new();
        store.Count.insert(OWNER, 0);

        let mut txn = store.begin_transaction(OWNER);
        txn.Count.with_mut(|v| *v = 1);
        txn.Items.insert("k", "v".to_owned());
        txn.commit().unwrap();

        assert_eq!(store.Count.get(OWNER), Some(1));
        assert_eq!(store.Items.get(OWNER, "k"), Some("v".to_owned()));
    }

    #[test]
    fn txn_singleton_with_mut_of_insert_in_same_txn_rolled_back_on_drop() {
        let store = KvStore::new();
        {
            let mut txn = store.begin_transaction(OWNER);
            txn.Count.insert(41);
            txn.Count.with_mut(|v| *v += 1);
            // dropped here without commit
        }
        assert_eq!(store.Count.get(OWNER), None);
    }

    #[test]
    fn txn_singleton_with_mut_over_existing_rolled_back_on_drop() {
        let store = KvStore::new();
        store.Count.insert(OWNER, 1);
        {
            let mut txn = store.begin_transaction(OWNER);
            txn.Count.with_mut(|v| *v += 1);
        }
        assert_eq!(store.Count.get(OWNER), Some(1));
    }

    #[test]
    fn txn_singleton_with_mut_explicitly_rolled_back() {
        let store = KvStore::new();
        store.Count.insert(OWNER, 1);

        let mut txn = store.begin_transaction(OWNER);
        txn.Count.with_mut(|v| *v += 1);
        txn.rollback();

        assert_eq!(store.Count.get(OWNER), Some(1));
    }

    #[test]
    fn txn_singleton_with_mut_after_rollback_sees_pre_txn_value() {
        let store = KvStore::new();
        store.Count.insert(OWNER, 1);
        {
            let mut txn = store.begin_transaction(OWNER);
            txn.Count.with_mut(|v| *v += 1);
        }

        let mut txn = store.begin_transaction(OWNER);
        let mut seen = None;
        txn.Count.with_mut(|v| seen = Some(*v));
        assert_eq!(seen, Some(1));
    }

    #[test]
    fn txn_singleton_insert_rolled_back_on_drop() {
        let store = KvStore::new();
        {
            let mut txn = store.begin_transaction(OWNER);
            txn.Count.insert(42);
            // dropped here without commit
        }
        assert_eq!(store.Count.get(OWNER), None);
    }

    #[test]
    fn txn_singleton_insert_over_existing_rolled_back_on_drop() {
        let store = KvStore::new();
        store.Count.insert(OWNER, 1);
        {
            let mut txn = store.begin_transaction(OWNER);
            txn.Count.insert(2);
        }
        assert_eq!(store.Count.get(OWNER), Some(1));
    }

    #[test]
    fn txn_singleton_remove_rolled_back_on_drop() {
        let store = KvStore::new();
        store.Count.insert(OWNER, 7);
        {
            let mut txn = store.begin_transaction(OWNER);
            txn.Count.remove();
        }
        assert_eq!(store.Count.get(OWNER), Some(7));
    }

    #[test]
    fn txn_table_insert_rolled_back_on_drop() {
        let store = KvStore::new();
        {
            let mut txn = store.begin_transaction(OWNER);
            txn.Items.insert("k", "v".to_owned());
        }
        assert_eq!(store.Items.get(OWNER, "k"), None);
    }

    #[test]
    fn txn_table_insert_over_existing_rolled_back_on_drop() {
        let store = KvStore::new();
        store.Items.insert(OWNER, "k", "orig".to_owned());
        {
            let mut txn = store.begin_transaction(OWNER);
            txn.Items.insert("k", "new".to_owned());
        }
        assert_eq!(store.Items.get(OWNER, "k"), Some("orig".to_owned()));
    }

    #[test]
    fn txn_table_mutate_rolled_back_on_drop() {
        let store = KvStore::new();
        store.Items.insert(OWNER, "k", "orig".to_owned());
        {
            let mut txn = store.begin_transaction(OWNER);
            txn.Items.with_mut(&"k", |v| *v = "new".to_owned());
        }
        assert_eq!(store.Items.get(OWNER, "k"), Some("orig".to_owned()));
    }

    #[test]
    fn txn_table_remove_rolled_back_on_drop() {
        let store = KvStore::new();
        store.Items.insert(OWNER, "k", "v".to_owned());
        {
            let mut txn = store.begin_transaction(OWNER);
            txn.Items.remove(&"k");
        }
        assert_eq!(store.Items.get(OWNER, "k"), Some("v".to_owned()));
    }

    #[test]
    fn txn_table_clear_rolled_back_on_drop() {
        let store = KvStore::new();
        store.Items.insert(OWNER, "a", "1".to_owned());
        store.Items.insert(OWNER, "b", "2".to_owned());
        {
            let mut txn = store.begin_transaction(OWNER);
            txn.Items.clear();
        }
        assert_eq!(store.Items.len(), 2);
    }

    #[test]
    fn txn_multiple_writes_all_visible_after_commit() {
        let store = KvStore::new();
        let mut txn = store.begin_transaction(OWNER);
        txn.Count.insert(1);
        txn.Items.insert("k", "v".to_owned());
        txn.Counters.insert(9u32, 99u64);
        txn.commit().unwrap();

        assert_eq!(store.Count.get(OWNER), Some(1));
        assert_eq!(store.Items.get(OWNER, "k"), Some("v".to_owned()));
        assert_eq!(store.Counters.get(OWNER, &9u32), Some(99));
    }

    #[test]
    fn txn_multiple_writes_none_visible_after_rollback() {
        let store = KvStore::new();
        {
            let mut txn = store.begin_transaction(OWNER);
            txn.Count.insert(1);
            txn.Items.insert("k", "v".to_owned());
            txn.Counters.insert(9u32, 99u64);
        }
        assert_eq!(store.Count.get(OWNER), None);
        assert_eq!(store.Items.get(OWNER, "k"), None);
        assert_eq!(store.Counters.get(OWNER, &9u32), None);
    }

    #[test]
    fn txn_mixed_insert_and_remove_commit_consistent() {
        let store = KvStore::new();
        store.Items.insert(OWNER, "keep", "old".to_owned());
        store.Items.insert(OWNER, "drop", "bye".to_owned());

        let mut txn = store.begin_transaction(OWNER);
        txn.Items.insert("keep", "new".to_owned());
        txn.Items.remove(&"drop");
        txn.Items.insert("add", "hi".to_owned());
        txn.commit().unwrap();

        let table = &store.Items;
        assert_eq!(table.get(OWNER, "keep"), Some("new".to_owned()));
        assert_eq!(table.get(OWNER, "drop"), None);
        assert_eq!(table.get(OWNER, "add"), Some("hi".to_owned()));
    }

    #[test]
    fn store_usable_after_rollback() {
        let store = KvStore::new();
        {
            let mut txn = store.begin_transaction(OWNER);
            txn.Count.insert(5);
        }
        assert_eq!(store.Count.get(OWNER), None);

        // A subsequent raw operation round-trips normally.
        store.Count.insert(OWNER, 9);
        assert_eq!(store.Count.get(OWNER), Some(9));
    }

    #[test]
    fn try_begin_transaction_succeeds_after_rollback() {
        let store = KvStore::new();
        {
            let mut txn = store.begin_transaction(OWNER);
            txn.Count.insert(1);
        }
        // The dropped transaction released the write lock.
        assert!(store.try_begin_transaction(OWNER).is_some());
    }

    #[test]
    fn new_txn_after_rollback_sees_committed_value() {
        let store = KvStore::new();
        store.Count.insert(OWNER, 1);
        {
            let mut txn = store.begin_transaction(OWNER);
            txn.Count.insert(2);
        }
        let txn2 = store.begin_transaction(OWNER);
        assert_eq!(txn2.Count.get(), Some(1));
    }

    #[test]
    fn panic_in_transaction_rolls_back() {
        let store = KvStore::new();
        store.Count.insert(OWNER, 1);

        std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
            let mut txn = store.begin_transaction(OWNER);
            txn.Count.insert(99);
            panic!();
        }))
        .unwrap_err();

        // The panicked transaction must have rolled back to the pre-transaction value.
        assert_eq!(store.Count.get(OWNER), Some(1));
    }

    #[test]
    fn panic_in_with_mut_rolls_back() {
        let store = KvStore::new();
        store.Items.insert(OWNER, "k", "a".to_owned());

        std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
            let mut txn = store.begin_transaction(OWNER);
            txn.Items.with_mut(&"k", |v| {
                *v = "b".to_owned();
                panic!();
            });
        }))
        .unwrap_err();

        // The mutation must be rolled back, both for the store itself and for the next
        // transaction (which is handed the same transaction id as the panicked one).
        assert_eq!(store.Items.get(OWNER, "k"), Some("a".to_owned()));
        let txn = store.begin_transaction(OWNER);
        assert_eq!(txn.Items.get(&"k"), Some("a".to_owned()));
    }

    #[test]
    fn store_recovers_after_panicked_transaction() {
        let store = KvStore::new();

        std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
            let mut txn = store.begin_transaction(OWNER);
            txn.Count.insert(5);
            panic!();
        }))
        .unwrap_err();

        // The store recovers from the poisoned lock and remains usable.
        store.Count.insert(OWNER, 7);
        assert_eq!(store.Count.get(OWNER), Some(7));

        let mut txn = store.begin_transaction(OWNER);
        txn.Count.insert(8);
        txn.commit().unwrap();
        assert_eq!(store.Count.get(OWNER), Some(8));
    }

    #[test]
    fn early_return_in_transaction_rolls_back() {
        let store = KvStore::new();
        store.Count.insert(OWNER, 1);

        // Returns early (without committing) when `fail` is set, otherwise commits.
        let run = |fail: bool| -> std::result::Result<(), ()> {
            let mut txn = store.begin_transaction(OWNER);
            txn.Count.insert(50);
            if fail {
                return Err(());
            }
            txn.commit().unwrap();
            Ok(())
        };

        assert!(run(true).is_err());
        assert_eq!(store.Count.get(OWNER), Some(1));

        assert!(run(false).is_ok());
        assert_eq!(store.Count.get(OWNER), Some(50));
    }

    #[test]
    fn singleton_three_commits_same_key_latest_wins() {
        let store = KvStore::new();

        for v in [10u64, 20, 30] {
            let mut txn = store.begin_transaction(OWNER);
            // Each transaction sees the value committed by the previous one.
            txn.Count.insert(v);
            txn.commit().unwrap();
            assert_eq!(store.Count.get(OWNER), Some(v));
        }
        assert_eq!(store.Count.get(OWNER), Some(30));
    }

    #[test]
    fn table_three_commits_same_key_latest_wins() {
        let store = KvStore::new();

        for v in ["one", "two", "three"] {
            let mut txn = store.begin_transaction(OWNER);
            txn.Items.insert("k", v.to_owned());
            txn.commit().unwrap();
            assert_eq!(store.Items.get(OWNER, "k"), Some(v.to_owned()));
        }
        assert_eq!(store.Items.get(OWNER, "k"), Some("three".to_owned()));
    }

    #[test]
    fn singleton_many_commits_same_key() {
        let store = KvStore::new();
        for v in 0..10u64 {
            let mut txn = store.begin_transaction(OWNER);
            txn.Count.insert(v);
            txn.commit().unwrap();
        }
        assert_eq!(store.Count.get(OWNER), Some(9));
    }

    // A new transaction begun after a rollback, with two committed versions of the key already
    // live in the two slots, must still observe the last committed value.
    #[test]
    fn singleton_rollback_after_two_commits_keeps_committed() {
        let store = KvStore::new();
        // First committed version (raw write).
        store.Count.insert(OWNER, 1);
        // Second committed version (fills the second slot).
        let mut txn = store.begin_transaction(OWNER);
        txn.Count.insert(2);
        txn.commit().unwrap();
        // Third write overwrites a slot, then rolls back.
        {
            let mut txn = store.begin_transaction(OWNER);
            txn.Count.insert(3);
        }
        assert_eq!(store.Count.get(OWNER), Some(2));
        // And a fresh transaction also sees the committed value, not the rolled-back one.
        let txn = store.begin_transaction(OWNER);
        assert_eq!(txn.Count.get(), Some(2));
    }

    #[test]
    fn table_rollback_after_two_commits_keeps_committed() {
        let store = KvStore::new();
        store.Items.insert(OWNER, "k", "v1".to_owned());
        let mut txn = store.begin_transaction(OWNER);
        txn.Items.insert("k", "v2".to_owned());
        txn.commit().unwrap();
        {
            let mut txn = store.begin_transaction(OWNER);
            txn.Items.insert("k", "v3".to_owned());
        }
        assert_eq!(store.Items.get(OWNER, "k"), Some("v2".to_owned()));
        let txn = store.begin_transaction(OWNER);
        assert_eq!(txn.Items.get("k"), Some("v2".to_owned()));
    }

    #[test]
    fn raw_insert_then_txn_overwrite_commit_visible_raw() {
        let store = KvStore::new();
        store.Count.insert(OWNER, 1);
        let mut txn = store.begin_transaction(OWNER);
        txn.Count.insert(2);
        txn.commit().unwrap();
        assert_eq!(store.Count.get(OWNER), Some(2));
    }

    #[test]
    fn txn_commit_then_raw_overwrite_then_txn_read() {
        let store = KvStore::new();
        let mut txn = store.begin_transaction(OWNER);
        txn.Count.insert(1);
        txn.commit().unwrap();

        // A raw write at the committed id overwrites the committed value...
        store.Count.insert(OWNER, 2);
        assert_eq!(store.Count.get(OWNER), Some(2));

        // ...and the next transaction observes it.
        let txn = store.begin_transaction(OWNER);
        assert_eq!(txn.Count.get(), Some(2));
    }

    #[test]
    fn raw_table_remove_then_txn_reinsert_commit() {
        let store = KvStore::new();
        store.Items.insert(OWNER, "k", "v".to_owned());
        store.Items.remove(OWNER, &"k");
        assert_eq!(store.Items.get(OWNER, "k"), None);

        let mut txn = store.begin_transaction(OWNER);
        txn.Items.insert("k", "again".to_owned());
        txn.commit().unwrap();
        assert_eq!(store.Items.get(OWNER, "k"), Some("again".to_owned()));
    }

    #[test]
    fn interleave_raw_and_txn_different_keys() {
        let store = KvStore::new();
        store.Items.insert(OWNER, "a", "A".to_owned());

        let mut txn = store.begin_transaction(OWNER);
        txn.Items.insert("b", "B".to_owned());
        txn.commit().unwrap();
        assert_eq!(store.Items.get(OWNER, "a"), Some("A".to_owned()));
        assert_eq!(store.Items.get(OWNER, "b"), Some("B".to_owned()));

        // A rolled-back transaction touching both keys leaves them as they were.
        {
            let mut txn = store.begin_transaction(OWNER);
            txn.Items.remove(&"a");
            txn.Items.insert("c", "C".to_owned());
        }
        assert_eq!(store.Items.get(OWNER, "a"), Some("A".to_owned()));
        assert_eq!(store.Items.get(OWNER, "c"), None);
    }

    #[test]
    fn txn_len_unchanged_after_removing_absent_key() {
        let store = KvStore::new();
        store.Items.insert(OWNER, "a", "1".to_owned());
        store.Items.insert(OWNER, "b", "2".to_owned());

        let mut txn = store.begin_transaction(OWNER);
        txn.Items.remove(&"zzz");
        assert_eq!(txn.Items.len(), 2);
    }

    #[test]
    fn txn_is_empty_false_after_removing_absent_key() {
        let store = KvStore::new();
        store.Items.insert(OWNER, "a", "1".to_owned());

        let mut txn = store.begin_transaction(OWNER);
        txn.Items.remove(&"zzz");
        assert!(!txn.Items.is_empty());
    }

    #[test]
    fn txn_len_after_removing_several_absent_keys() {
        let store = KvStore::new();
        store.Items.insert(OWNER, "a", "1".to_owned());

        let mut txn = store.begin_transaction(OWNER);
        txn.Items.remove(&"x");
        txn.Items.remove(&"y");
        txn.Items.remove(&"z");
        assert_eq!(txn.Items.len(), 1);
    }

    #[test]
    fn txn_len_reflects_mixed_insert_remove() {
        let store = KvStore::new();
        store.Items.insert(OWNER, "a", "1".to_owned());
        store.Items.insert(OWNER, "b", "2".to_owned());
        store.Items.insert(OWNER, "c", "3".to_owned());

        let mut txn = store.begin_transaction(OWNER);
        txn.Items.remove(&"b");
        txn.Items.insert("d", "4".to_owned());
        assert_eq!(txn.Items.len(), 3);
    }

    #[test]
    fn txn_iter_reflects_committed_plus_pending_minus_removed() {
        let store = KvStore::new();
        store.Items.insert(OWNER, "a", "1".to_owned());
        store.Items.insert(OWNER, "b", "2".to_owned());
        store.Items.insert(OWNER, "c", "3".to_owned());

        let mut txn = store.begin_transaction(OWNER);
        txn.Items.remove(&"b");
        txn.Items.insert("d", "4".to_owned());

        let table = &txn.Items;
        let mut keys: Vec<_> = table.keys().copied().collect();
        keys.sort();
        assert_eq!(keys, vec!["a", "c", "d"]);
    }

    #[test]
    fn txn_clear_then_insert_len_and_iter() {
        let store = KvStore::new();
        store.Items.insert(OWNER, "a", "1".to_owned());
        store.Items.insert(OWNER, "b", "2".to_owned());

        let mut txn = store.begin_transaction(OWNER);
        txn.Items.clear();
        txn.Items.insert("x", "9".to_owned());

        let table = &txn.Items;
        assert_eq!(table.len(), 1);
        let keys: Vec<_> = table.keys().copied().collect();
        assert_eq!(keys, vec!["x"]);
    }

    #[test]
    fn txn_is_empty_after_clear() {
        let store = KvStore::new();
        store.Items.insert(OWNER, "a", "1".to_owned());
        store.Items.insert(OWNER, "b", "2".to_owned());

        let mut txn = store.begin_transaction(OWNER);
        txn.Items.clear();
        assert!(txn.Items.is_empty());
        assert_eq!(txn.Items.len(), 0);
    }

    #[test]
    fn txn_mutate_committed_value_commit_persists() {
        let store = KvStore::new();
        store.Items.insert(OWNER, "k", "orig".to_owned());

        let mut txn = store.begin_transaction(OWNER);
        txn.Items.with_mut(&"k", |v| v.push('!'));
        txn.commit().unwrap();

        assert_eq!(store.Items.get(OWNER, "k"), Some("orig!".to_owned()));
    }

    #[test]
    fn txn_iter_mut_committed_values_commit_persists() {
        let store = KvStore::new();
        store.Items.insert(OWNER, "a", "x".to_owned());
        store.Items.insert(OWNER, "b", "y".to_owned());

        let mut txn = store.begin_transaction(OWNER);
        for (_, v) in txn.Items.iter_mut() {
            v.push('!');
        }
        for v in txn.Items.values_mut() {
            v.push('!');
        }
        txn.commit().unwrap();

        assert_eq!(store.Items.get(OWNER, "a"), Some("x!!".to_owned()));
        assert_eq!(store.Items.get(OWNER, "b"), Some("y!!".to_owned()));
    }

    #[test]
    fn ro_txn_after_commit_sees_committed() {
        let store = KvStore::new();
        let mut txn = store.begin_transaction(OWNER);
        txn.Count.insert(7);
        txn.commit().unwrap();

        let txn = store.begin_ro_transaction(OWNER);
        assert_eq!(txn.Count.get(), Some(7));
    }

    #[test]
    fn ro_txn_after_rollback_sees_pre_txn() {
        let store = KvStore::new();
        store.Count.insert(OWNER, 1);
        {
            let mut txn = store.begin_transaction(OWNER);
            txn.Count.insert(2);
        }
        let txn = store.begin_ro_transaction(OWNER);
        assert_eq!(txn.Count.get(), Some(1));
    }

    #[test]
    fn ro_txn_after_multiple_commits_sees_latest() {
        let store = KvStore::new();
        for v in [10u64, 20, 30] {
            let mut txn = store.begin_transaction(OWNER);
            txn.Count.insert(v);
            txn.commit().unwrap();
        }
        let txn = store.begin_ro_transaction(OWNER);
        assert_eq!(txn.Count.get(), Some(30));
    }

    #[test]
    fn try_begin_transaction_none_while_rw_txn_active() {
        let store = KvStore::new();
        let _txn = store.begin_transaction(OWNER);
        assert!(store.try_begin_transaction(OWNER).is_none());
    }

    #[test]
    fn try_begin_ro_transaction_none_while_rw_txn_active() {
        let store = KvStore::new();
        let _txn = store.begin_transaction(OWNER);
        assert!(store.try_begin_ro_transaction(OWNER).is_none());
    }

    #[test]
    fn try_begin_transaction_none_while_ro_txn_active() {
        let store = KvStore::new();
        let _txn = store.begin_ro_transaction(OWNER);
        assert!(store.try_begin_transaction(OWNER).is_none());
    }

    // The tests below exist to pin down which combinations of accessors may be held at the same
    // time. They are as much compile-time tests as run-time ones: if the accessors stop being
    // disjoint borrows of the transaction, these stop compiling.

    #[test]
    fn two_tables_of_one_txn_are_mutable_at_once() {
        let store = KvStore::new();
        let mut txn = store.begin_transaction(OWNER);

        let items = &mut txn.Items;
        let counters = &mut txn.Counters;

        items.insert("k", "v".to_owned());
        counters.insert(1, 7);
        assert_eq!(items.get(&"k"), Some("v".to_owned()));
        assert_eq!(counters.get(&1), Some(7));

        txn.commit().unwrap();
        assert_eq!(store.Items.get(OWNER, "k"), Some("v".to_owned()));
        assert_eq!(store.Counters.get(OWNER, &1), Some(7));
    }

    #[test]
    fn a_table_and_a_singleton_of_one_txn_are_mutable_at_once() {
        let store = KvStore::new();
        let mut txn = store.begin_transaction(OWNER);

        let items = &mut txn.Items;
        let count = &mut txn.Count;

        items.insert("k", "v".to_owned());
        count.insert(7);
        assert_eq!(items.get(&"k"), Some("v".to_owned()));
        assert_eq!(count.get(), Some(7));

        txn.commit().unwrap();
        assert_eq!(store.Items.get(OWNER, "k"), Some("v".to_owned()));
        assert_eq!(store.Count.get(OWNER), Some(7));
    }

    #[test]
    fn two_ro_tables_of_one_txn_are_readable_at_once() {
        let store = KvStore::new();
        store.Items.insert(OWNER, "k", "v".to_owned());
        store.Counters.insert(OWNER, 1, 7);

        let txn = store.begin_ro_transaction(OWNER);
        let items = &txn.Items;
        let counters = &txn.Counters;

        assert_eq!(items.get(&"k"), Some("v".to_owned()));
        assert_eq!(counters.get(&1), Some(7));
    }
}
